
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_network.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_NETWORK_H
#define __STAI_ATON_NETWORK_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_NETWORK_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_NETWORK_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_network_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_network_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_network_get_context_size(void)
{
  return STAI_NETWORK_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_network_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_network_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_network_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_network_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_NETWORK_STATES_NUM  (0)
#define STAI_NETWORK_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_NETWORK_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_NETWORK_IN_NUM (1)
#define STAI_NETWORK_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_NETWORK_IN_FORMATS \
  { \
    STAI_FORMAT_U8 \
  }
#define STAI_NETWORK_IN_SIZES \
  { \
    3200 \
  }
#define STAI_NETWORK_IN_SIZES_BYTES \
  { \
    3200 \
  }

#define STAI_NETWORK_IN_1_ALIGNMENT (32)
#define STAI_NETWORK_IN_1_NAME "Input_0_out_0"
#define STAI_NETWORK_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_IN_1_FORMAT (STAI_FORMAT_U8)
#define STAI_NETWORK_IN_1_SIZE (3200)
#define STAI_NETWORK_IN_1_SIZE_BYTES (3200)
#define STAI_NETWORK_IN_1_CHANNEL (1)
#define STAI_NETWORK_IN_1_HEIGHT (50)
#define STAI_NETWORK_IN_1_WIDTH (64)
#define STAI_NETWORK_IN_1_BATCH (1)
#define STAI_NETWORK_IN_1_RANK (4)
#define STAI_NETWORK_IN_1_SHAPE \
  { \
    1, 50, 64, 1 \
  }
#define STAI_NETWORK_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_IN_1_SCALES \
  { \
    1 \
  }
#define STAI_NETWORK_IN_1_OFFSETS \
  { \
    0 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_NETWORK_OUT_NUM (1)
#define STAI_NETWORK_OUT_ALIGNMENTS \
  { \
    16 \
  }
#define STAI_NETWORK_OUT_NAMES \
  { \
    "Quantize_37_out_0" \
  }
#define STAI_NETWORK_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_OUT_SIZES \
  { \
    4 \
  }
#define STAI_NETWORK_OUT_SIZES_BYTES \
  { \
    4 \
  }

#define STAI_NETWORK_OUT_1_ALIGNMENT (16)
#define STAI_NETWORK_OUT_1_NAME "Quantize_37_out_0"
#define STAI_NETWORK_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_NETWORK_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_OUT_1_SIZE (4)
#define STAI_NETWORK_OUT_1_SIZE_BYTES (4)
#define STAI_NETWORK_OUT_1_CHANNEL (1)
#define STAI_NETWORK_OUT_1_HEIGHT (1)
#define STAI_NETWORK_OUT_1_WIDTH (4)
#define STAI_NETWORK_OUT_1_RANK (2)
#define STAI_NETWORK_OUT_1_SHAPE \
  { \
    1, 4 \
  }
#define STAI_NETWORK_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_NETWORK_OUT_1_OFFSETS \
  { \
    -128 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_WEIGHTS_NUM (31)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
    16, 16, 16, 32, 32, 32, 32, 32, 32, 16, 16, 16, 32, 16, 16, 16, 32, 16, 16, 16, 32, 16, 16, 16, 16, 16, 32, 32, 32, 16, 16 \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
    "Quantize_3_y_scale", "Quantize_3_y_zero_point", "Conv2D_5_weights", "Conv2D_11_weights", "Conv2D_17_weights", "Conv2D_23_weights", "Gemm_29_weights_transposed_3", "Gemm_33_weights_transposed_9", "Conv2D_5_zero_off_14", "Conv2D_5_off_bias_20", "Conv2D_11_zero_off_23", "Conv2D_11_off_bias_29", "Conv2D_17_zero_off_32", "Conv2D_17_off_bias_38", "Conv2D_23_zero_off_41", "Conv2D_23_off_bias_47", "Gemm_29_conv_4_zero_off_50", "Gemm_29_conv_4_off_bias_56", "Gemm_33_conv_10_zero_off_59", "Gemm_33_conv_10_off_bias_65", "RequantizeLinear_inserted_id180_182_requantize_zero", "Conv2D_5_off_bias_18_A_16_184", "Conv2D_11_off_bias_27_A_16_186", "Conv2D_17_off_bias_36_A_16_188", "Conv2D_23_off_bias_45_A_16_190", "Gemm_29_conv_4_off_bias_54_A_16_192", "Gemm_33_conv_10_off_bias_63_A_16_194", "Gemm_33_squeeze_y_11_196_atonn_internal_scale", "Gemm_33_squeeze_y_11_196_atonn_internal_offset", "Softmax_36_200_atonn_internal_scale", "Softmax_36_200_atonn_internal_offset" \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_FLOAT32, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_Q7, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
    1, 1, 144, 4608, 13824, 27648, 2048, 128, 1, 16, 1, 32, 1, 48, 1, 64, 1, 32, 1, 4, 1, 16, 32, 48, 64, 32, 4, 1, 1, 1, 1 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
    4, 1, 144, 4608, 13824, 27648, 2048, 128, 1, 64, 1, 128, 1, 192, 1, 256, 1, 128, 1, 16, 1, 32, 64, 96, 128, 64, 8, 4, 1, 4, 1 \
  }

#define STAI_NETWORK_WEIGHTS_1_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_1_NAME "Quantize_3_y_scale"
#define STAI_NETWORK_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_1_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_NETWORK_WEIGHTS_1_SIZE (1)
#define STAI_NETWORK_WEIGHTS_1_SIZE_BYTES (4)
#define STAI_NETWORK_WEIGHTS_1_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_1_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_1_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_1_RANK (1)
#define STAI_NETWORK_WEIGHTS_1_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_1_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_1_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_1_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_2_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_2_NAME "Quantize_3_y_zero_point"
#define STAI_NETWORK_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_2_SIZE (1)
#define STAI_NETWORK_WEIGHTS_2_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_2_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_2_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_2_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_2_RANK (1)
#define STAI_NETWORK_WEIGHTS_2_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_2_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_2_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_2_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_3_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_3_NAME "Conv2D_5_weights"
#define STAI_NETWORK_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_3_SIZE (144)
#define STAI_NETWORK_WEIGHTS_3_SIZE_BYTES (144)
#define STAI_NETWORK_WEIGHTS_3_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_3_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_3_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_3_BATCH (1)
#define STAI_NETWORK_WEIGHTS_3_RANK (4)
#define STAI_NETWORK_WEIGHTS_3_SHAPE \
  { \
    16, 3, 3, 1 \
  }
#define STAI_NETWORK_WEIGHTS_3_SCALE_OFFSET_NUM (16)
#define STAI_NETWORK_WEIGHTS_3_SCALES \
  { \
    7.32804892322747e-06, 6.85541726852534e-06, 6.83572534398991e-06, 6.34826801615418e-06, 8.44727310322924e-06, 7.31310728951939e-06, 9.84220969257876e-06, 6.55631083645858e-06, 9.99922394839814e-06, 5.86729220231064e-06, 7.87944463809254e-06, 1.083369988919e-05, 8.23253958515124e-06, 5.60493708690046e-06, 6.98257508702227e-06, 1.0896142157435e-05 \
  }
#define STAI_NETWORK_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_4_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_4_NAME "Conv2D_11_weights"
#define STAI_NETWORK_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_4_SIZE (4608)
#define STAI_NETWORK_WEIGHTS_4_SIZE_BYTES (4608)
#define STAI_NETWORK_WEIGHTS_4_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_4_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_4_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_4_BATCH (8)
#define STAI_NETWORK_WEIGHTS_4_RANK (5)
#define STAI_NETWORK_WEIGHTS_4_SHAPE \
  { \
    32, 2, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_4_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_4_SCALES \
  { \
    0.00145564030390233, 0.00154568732250482, 0.00207707798108459, 0.00149148632772267, 0.00169401289895177, 0.00179507618304342, 0.00124360038898885, 0.00191953196190298, 0.00185089255683124, 0.00144522427581251, 0.00164411088917404, 0.00184684793930501, 0.00172168086282909, 0.00175155221950263, 0.00212636147625744, 0.00184782745782286, 0.00146176957059652, 0.0017099897377193, 0.00195118924602866, 0.00176696677226573, 0.00192769034765661, 0.00141070783138275, 0.00156306417193264, 0.00151849526446313, 0.00213623512536287, 0.00192026456352323, 0.00197742669843137, 0.00200469489209354, 0.00219133915379643, 0.0023462891113013, 0.00172889488749206, 0.00195099727716297 \
  }
#define STAI_NETWORK_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_5_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_5_NAME "Conv2D_17_weights"
#define STAI_NETWORK_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_5_SIZE (13824)
#define STAI_NETWORK_WEIGHTS_5_SIZE_BYTES (13824)
#define STAI_NETWORK_WEIGHTS_5_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_5_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_5_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_5_BATCH (8)
#define STAI_NETWORK_WEIGHTS_5_RANK (5)
#define STAI_NETWORK_WEIGHTS_5_SHAPE \
  { \
    48, 4, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_5_SCALE_OFFSET_NUM (48)
#define STAI_NETWORK_WEIGHTS_5_SCALES \
  { \
    0.00161410751752555, 0.00127408059779555, 0.00257274648174644, 0.00118796969763935, 0.00253918231464922, 0.00180381152313203, 0.00255420315079391, 0.00139383506029844, 0.00124065415002406, 0.00170759216416627, 0.00118684943299741, 0.00212764390744269, 0.00123527273535728, 0.00192774157039821, 0.00174834649078548, 0.00109159003477544, 0.00202067312784493, 0.00190895586274564, 0.00161256140563637, 0.00135549332480878, 0.00179887318518013, 0.00164581381250173, 0.00192608509678394, 0.0019819843582809, 0.00257601123303175, 0.00134755636099726, 0.00175549078267068, 0.00190155603922904, 0.00256956159137189, 0.00142084108665586, 0.00171060103457421, 0.0010402244515717, 0.00101765594445169, 0.00127388641703874, 0.00172688451129943, 0.00112622161395848, 0.0013182214461267, 0.00118038186337799, 0.00172415457200259, 0.00212715868838131, 0.00146554701495916, 0.00259803677909076, 0.00154917128384113, 0.00180691154673696, 0.00190488726366311, 0.00134409929160029, 0.00124208175111562, 0.00224788929335773 \
  }
#define STAI_NETWORK_WEIGHTS_5_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_6_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_6_NAME "Conv2D_23_weights"
#define STAI_NETWORK_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_6_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_6_SIZE (27648)
#define STAI_NETWORK_WEIGHTS_6_SIZE_BYTES (27648)
#define STAI_NETWORK_WEIGHTS_6_CHANNEL (48)
#define STAI_NETWORK_WEIGHTS_6_HEIGHT (3)
#define STAI_NETWORK_WEIGHTS_6_WIDTH (3)
#define STAI_NETWORK_WEIGHTS_6_BATCH (8)
#define STAI_NETWORK_WEIGHTS_6_RANK (5)
#define STAI_NETWORK_WEIGHTS_6_SHAPE \
  { \
    64, 6, 3, 3, 8 \
  }
#define STAI_NETWORK_WEIGHTS_6_SCALE_OFFSET_NUM (64)
#define STAI_NETWORK_WEIGHTS_6_SCALES \
  { \
    0.0023493601474911, 0.000851493910886347, 0.00232940469868481, 0.00176164810545743, 0.00126153824385256, 0.00128694751765579, 0.00215879268944263, 0.00210433173924685, 0.00180605833884329, 0.00117027992382646, 0.00111185293644667, 0.00256357016041875, 0.00113979983143508, 0.00117800466250628, 0.00296178879216313, 0.00155281170736998, 0.0013455149019137, 0.00128872191999108, 0.00113471003714949, 0.00275940634310246, 0.00233186315745115, 0.00251144822686911, 0.00173690856900066, 0.0017031755996868, 0.00321991136297584, 0.00197017216123641, 0.00130806863307953, 0.00250678020529449, 0.00240313541144133, 0.00148277007974684, 0.0013800096930936, 0.00148592505138367, 0.00170216278638691, 0.00264712097123265, 0.001797093776986, 0.00155833677854389, 0.00117255817167461, 0.00203057704493403, 0.00138018082361668, 0.00198363186791539, 0.00260058394633234, 0.00180748978164047, 0.00115951569750905, 0.00122129695955664, 0.00217479933053255, 0.00101117545273155, 0.00342464447021484, 0.00278942543081939, 0.00262483116239309, 0.00138696364592761, 0.00288132182322443, 0.00216816342435777, 0.00121719902381301, 0.00289394496940076, 0.00174019765108824, 0.00142787466756999, 0.0022950975690037, 0.00113642716314644, 0.00137294153682888, 0.00137929047923535, 0.00263286894187331, 0.00203878432512283, 0.00162611284758896, 0.00120146013796329 \
  }
#define STAI_NETWORK_WEIGHTS_6_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_7_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_7_NAME "Gemm_29_weights_transposed_3"
#define STAI_NETWORK_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_7_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_7_SIZE (2048)
#define STAI_NETWORK_WEIGHTS_7_SIZE_BYTES (2048)
#define STAI_NETWORK_WEIGHTS_7_CHANNEL (64)
#define STAI_NETWORK_WEIGHTS_7_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_7_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_7_BATCH (64)
#define STAI_NETWORK_WEIGHTS_7_RANK (4)
#define STAI_NETWORK_WEIGHTS_7_SHAPE \
  { \
    32, 1, 1, 64 \
  }
#define STAI_NETWORK_WEIGHTS_7_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_7_SCALES \
  { \
    0.00275375763885677, 0.00194528070278466, 0.00201192335225642, 0.00202447967603803, 0.00243983720429242, 0.00265906541608274, 0.00296067586168647, 0.00199472391977906, 0.00196741637773812, 0.00250955228693783, 0.00300710066221654, 0.002800831804052, 0.00284898933023214, 0.00322153838351369, 0.00247603864409029, 0.00271229329518974, 0.00242857355624437, 0.002118258504197, 0.00342436041682959, 0.00188969622831792, 0.00265598925761878, 0.00197079824283719, 0.00246109697036445, 0.00198406889103353, 0.00328006315976381, 0.00215643784031272, 0.00255892612040043, 0.00237381528131664, 0.00331959524191916, 0.00226410897448659, 0.00229293364100158, 0.0029486243147403 \
  }
#define STAI_NETWORK_WEIGHTS_7_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_8_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_8_NAME "Gemm_33_weights_transposed_9"
#define STAI_NETWORK_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_8_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_8_SIZE (128)
#define STAI_NETWORK_WEIGHTS_8_SIZE_BYTES (128)
#define STAI_NETWORK_WEIGHTS_8_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_8_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_8_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_8_BATCH (32)
#define STAI_NETWORK_WEIGHTS_8_RANK (4)
#define STAI_NETWORK_WEIGHTS_8_SHAPE \
  { \
    4, 1, 1, 32 \
  }
#define STAI_NETWORK_WEIGHTS_8_SCALE_OFFSET_NUM (4)
#define STAI_NETWORK_WEIGHTS_8_SCALES \
  { \
    0.00420345040038228, 0.00339680816978216, 0.00393129559233785, 0.00429228600114584 \
  }
#define STAI_NETWORK_WEIGHTS_8_OFFSETS \
  { \
    0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_9_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_9_NAME "Conv2D_5_zero_off_14"
#define STAI_NETWORK_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_9_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_9_SIZE (1)
#define STAI_NETWORK_WEIGHTS_9_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_9_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_9_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_9_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_9_RANK (1)
#define STAI_NETWORK_WEIGHTS_9_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_9_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_9_SCALES \
  { \
    0.996078431606293 \
  }
#define STAI_NETWORK_WEIGHTS_9_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_10_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_10_NAME "Conv2D_5_off_bias_20"
#define STAI_NETWORK_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_10_FORMAT (STAI_FORMAT_S32)
#define STAI_NETWORK_WEIGHTS_10_SIZE (16)
#define STAI_NETWORK_WEIGHTS_10_SIZE_BYTES (64)
#define STAI_NETWORK_WEIGHTS_10_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_10_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_10_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_10_BATCH (8)
#define STAI_NETWORK_WEIGHTS_10_RANK (4)
#define STAI_NETWORK_WEIGHTS_10_SHAPE \
  { \
    2, 1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_10_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_10_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_10_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_11_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_11_NAME "Conv2D_11_zero_off_23"
#define STAI_NETWORK_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_11_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_11_SIZE (1)
#define STAI_NETWORK_WEIGHTS_11_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_11_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_11_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_11_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_11_RANK (1)
#define STAI_NETWORK_WEIGHTS_11_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_11_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_11_SCALES \
  { \
    0.00437555555254221 \
  }
#define STAI_NETWORK_WEIGHTS_11_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_12_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_12_NAME "Conv2D_11_off_bias_29"
#define STAI_NETWORK_WEIGHTS_12_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_12_FORMAT (STAI_FORMAT_S32)
#define STAI_NETWORK_WEIGHTS_12_SIZE (32)
#define STAI_NETWORK_WEIGHTS_12_SIZE_BYTES (128)
#define STAI_NETWORK_WEIGHTS_12_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_12_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_12_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_12_BATCH (8)
#define STAI_NETWORK_WEIGHTS_12_RANK (4)
#define STAI_NETWORK_WEIGHTS_12_SHAPE \
  { \
    4, 1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_12_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_12_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_12_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_13_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_13_NAME "Conv2D_17_zero_off_32"
#define STAI_NETWORK_WEIGHTS_13_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_13_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_13_SIZE (1)
#define STAI_NETWORK_WEIGHTS_13_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_13_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_13_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_13_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_13_RANK (1)
#define STAI_NETWORK_WEIGHTS_13_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_13_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_13_SCALES \
  { \
    0.0108856549486518 \
  }
#define STAI_NETWORK_WEIGHTS_13_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_14_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_14_NAME "Conv2D_17_off_bias_38"
#define STAI_NETWORK_WEIGHTS_14_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_14_FORMAT (STAI_FORMAT_S32)
#define STAI_NETWORK_WEIGHTS_14_SIZE (48)
#define STAI_NETWORK_WEIGHTS_14_SIZE_BYTES (192)
#define STAI_NETWORK_WEIGHTS_14_CHANNEL (48)
#define STAI_NETWORK_WEIGHTS_14_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_14_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_14_BATCH (8)
#define STAI_NETWORK_WEIGHTS_14_RANK (4)
#define STAI_NETWORK_WEIGHTS_14_SHAPE \
  { \
    6, 1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_14_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_14_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_14_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_15_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_15_NAME "Conv2D_23_zero_off_41"
#define STAI_NETWORK_WEIGHTS_15_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_15_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_15_SIZE (1)
#define STAI_NETWORK_WEIGHTS_15_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_15_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_15_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_15_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_15_RANK (1)
#define STAI_NETWORK_WEIGHTS_15_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_15_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_15_SCALES \
  { \
    0.0284173991531134 \
  }
#define STAI_NETWORK_WEIGHTS_15_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_16_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_16_NAME "Conv2D_23_off_bias_47"
#define STAI_NETWORK_WEIGHTS_16_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_16_FORMAT (STAI_FORMAT_S32)
#define STAI_NETWORK_WEIGHTS_16_SIZE (64)
#define STAI_NETWORK_WEIGHTS_16_SIZE_BYTES (256)
#define STAI_NETWORK_WEIGHTS_16_CHANNEL (64)
#define STAI_NETWORK_WEIGHTS_16_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_16_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_16_BATCH (8)
#define STAI_NETWORK_WEIGHTS_16_RANK (4)
#define STAI_NETWORK_WEIGHTS_16_SHAPE \
  { \
    8, 1, 1, 8 \
  }
#define STAI_NETWORK_WEIGHTS_16_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_16_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_16_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_17_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_17_NAME "Gemm_29_conv_4_zero_off_50"
#define STAI_NETWORK_WEIGHTS_17_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_17_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_17_SIZE (1)
#define STAI_NETWORK_WEIGHTS_17_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_17_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_17_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_17_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_17_RANK (1)
#define STAI_NETWORK_WEIGHTS_17_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_17_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_17_SCALES \
  { \
    0.0253982152789831 \
  }
#define STAI_NETWORK_WEIGHTS_17_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_18_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_18_NAME "Gemm_29_conv_4_off_bias_56"
#define STAI_NETWORK_WEIGHTS_18_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_NETWORK_WEIGHTS_18_FORMAT (STAI_FORMAT_S32)
#define STAI_NETWORK_WEIGHTS_18_SIZE (32)
#define STAI_NETWORK_WEIGHTS_18_SIZE_BYTES (128)
#define STAI_NETWORK_WEIGHTS_18_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_18_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_18_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_18_BATCH (16)
#define STAI_NETWORK_WEIGHTS_18_RANK (4)
#define STAI_NETWORK_WEIGHTS_18_SHAPE \
  { \
    2, 1, 1, 16 \
  }
#define STAI_NETWORK_WEIGHTS_18_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_18_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_18_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_19_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_19_NAME "Gemm_33_conv_10_zero_off_59"
#define STAI_NETWORK_WEIGHTS_19_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_19_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_19_SIZE (1)
#define STAI_NETWORK_WEIGHTS_19_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_19_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_19_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_19_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_19_RANK (1)
#define STAI_NETWORK_WEIGHTS_19_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_19_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_19_SCALES \
  { \
    0.0386359803378582 \
  }
#define STAI_NETWORK_WEIGHTS_19_OFFSETS \
  { \
    0 \
  }

#define STAI_NETWORK_WEIGHTS_20_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_20_NAME "Gemm_33_conv_10_off_bias_65"
#define STAI_NETWORK_WEIGHTS_20_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_20_FORMAT (STAI_FORMAT_S32)
#define STAI_NETWORK_WEIGHTS_20_SIZE (4)
#define STAI_NETWORK_WEIGHTS_20_SIZE_BYTES (16)
#define STAI_NETWORK_WEIGHTS_20_CHANNEL (4)
#define STAI_NETWORK_WEIGHTS_20_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_20_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_20_BATCH (4)
#define STAI_NETWORK_WEIGHTS_20_RANK (3)
#define STAI_NETWORK_WEIGHTS_20_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_NETWORK_WEIGHTS_20_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_20_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_20_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_21_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_21_NAME "RequantizeLinear_inserted_id180_182_requantize_zero"
#define STAI_NETWORK_WEIGHTS_21_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_21_FORMAT (STAI_FORMAT_Q7)
#define STAI_NETWORK_WEIGHTS_21_SIZE (1)
#define STAI_NETWORK_WEIGHTS_21_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_21_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_21_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_21_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_21_BATCH (1)
#define STAI_NETWORK_WEIGHTS_21_RANK (4)
#define STAI_NETWORK_WEIGHTS_21_SHAPE \
  { \
    1, 1, 1, 1 \
  }
#define STAI_NETWORK_WEIGHTS_21_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_21_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_21_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_22_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_22_NAME "Conv2D_5_off_bias_18_A_16_184"
#define STAI_NETWORK_WEIGHTS_22_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_22_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_22_SIZE (16)
#define STAI_NETWORK_WEIGHTS_22_SIZE_BYTES (32)
#define STAI_NETWORK_WEIGHTS_22_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_22_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_22_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_22_BATCH (16)
#define STAI_NETWORK_WEIGHTS_22_RANK (3)
#define STAI_NETWORK_WEIGHTS_22_SHAPE \
  { \
    1, 1, 16 \
  }
#define STAI_NETWORK_WEIGHTS_22_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_22_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_22_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_23_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_23_NAME "Conv2D_11_off_bias_27_A_16_186"
#define STAI_NETWORK_WEIGHTS_23_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_23_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_23_SIZE (32)
#define STAI_NETWORK_WEIGHTS_23_SIZE_BYTES (64)
#define STAI_NETWORK_WEIGHTS_23_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_23_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_23_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_23_BATCH (32)
#define STAI_NETWORK_WEIGHTS_23_RANK (3)
#define STAI_NETWORK_WEIGHTS_23_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_NETWORK_WEIGHTS_23_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_23_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_23_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_24_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_24_NAME "Conv2D_17_off_bias_36_A_16_188"
#define STAI_NETWORK_WEIGHTS_24_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_24_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_24_SIZE (48)
#define STAI_NETWORK_WEIGHTS_24_SIZE_BYTES (96)
#define STAI_NETWORK_WEIGHTS_24_CHANNEL (48)
#define STAI_NETWORK_WEIGHTS_24_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_24_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_24_BATCH (48)
#define STAI_NETWORK_WEIGHTS_24_RANK (3)
#define STAI_NETWORK_WEIGHTS_24_SHAPE \
  { \
    1, 1, 48 \
  }
#define STAI_NETWORK_WEIGHTS_24_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_24_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_24_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_25_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_25_NAME "Conv2D_23_off_bias_45_A_16_190"
#define STAI_NETWORK_WEIGHTS_25_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_25_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_25_SIZE (64)
#define STAI_NETWORK_WEIGHTS_25_SIZE_BYTES (128)
#define STAI_NETWORK_WEIGHTS_25_CHANNEL (64)
#define STAI_NETWORK_WEIGHTS_25_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_25_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_25_BATCH (64)
#define STAI_NETWORK_WEIGHTS_25_RANK (3)
#define STAI_NETWORK_WEIGHTS_25_SHAPE \
  { \
    1, 1, 64 \
  }
#define STAI_NETWORK_WEIGHTS_25_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_25_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_25_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_26_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_26_NAME "Gemm_29_conv_4_off_bias_54_A_16_192"
#define STAI_NETWORK_WEIGHTS_26_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_26_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_26_SIZE (32)
#define STAI_NETWORK_WEIGHTS_26_SIZE_BYTES (64)
#define STAI_NETWORK_WEIGHTS_26_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_26_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_26_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_26_BATCH (32)
#define STAI_NETWORK_WEIGHTS_26_RANK (3)
#define STAI_NETWORK_WEIGHTS_26_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_NETWORK_WEIGHTS_26_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_26_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_26_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_27_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_27_NAME "Gemm_33_conv_10_off_bias_63_A_16_194"
#define STAI_NETWORK_WEIGHTS_27_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_27_FORMAT (STAI_FORMAT_Q15)
#define STAI_NETWORK_WEIGHTS_27_SIZE (4)
#define STAI_NETWORK_WEIGHTS_27_SIZE_BYTES (8)
#define STAI_NETWORK_WEIGHTS_27_CHANNEL (4)
#define STAI_NETWORK_WEIGHTS_27_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_27_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_27_BATCH (4)
#define STAI_NETWORK_WEIGHTS_27_RANK (3)
#define STAI_NETWORK_WEIGHTS_27_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_NETWORK_WEIGHTS_27_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_27_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_27_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_28_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_28_NAME "Gemm_33_squeeze_y_11_196_atonn_internal_scale"
#define STAI_NETWORK_WEIGHTS_28_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_28_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_NETWORK_WEIGHTS_28_SIZE (1)
#define STAI_NETWORK_WEIGHTS_28_SIZE_BYTES (4)
#define STAI_NETWORK_WEIGHTS_28_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_28_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_28_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_28_RANK (1)
#define STAI_NETWORK_WEIGHTS_28_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_28_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_28_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_28_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_29_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_29_NAME "Gemm_33_squeeze_y_11_196_atonn_internal_offset"
#define STAI_NETWORK_WEIGHTS_29_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_29_FORMAT (STAI_FORMAT_Q7)
#define STAI_NETWORK_WEIGHTS_29_SIZE (1)
#define STAI_NETWORK_WEIGHTS_29_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_29_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_29_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_29_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_29_RANK (1)
#define STAI_NETWORK_WEIGHTS_29_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_29_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_29_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_29_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_30_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_30_NAME "Softmax_36_200_atonn_internal_scale"
#define STAI_NETWORK_WEIGHTS_30_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_30_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_NETWORK_WEIGHTS_30_SIZE (1)
#define STAI_NETWORK_WEIGHTS_30_SIZE_BYTES (4)
#define STAI_NETWORK_WEIGHTS_30_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_30_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_30_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_30_RANK (1)
#define STAI_NETWORK_WEIGHTS_30_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_30_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_30_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_30_OFFSETS \
  { \
  }

#define STAI_NETWORK_WEIGHTS_31_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_31_NAME "Softmax_36_200_atonn_internal_offset"
#define STAI_NETWORK_WEIGHTS_31_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_WEIGHTS_31_FORMAT (STAI_FORMAT_Q7)
#define STAI_NETWORK_WEIGHTS_31_SIZE (1)
#define STAI_NETWORK_WEIGHTS_31_SIZE_BYTES (1)
#define STAI_NETWORK_WEIGHTS_31_CHANNEL (1)
#define STAI_NETWORK_WEIGHTS_31_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_31_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_31_RANK (1)
#define STAI_NETWORK_WEIGHTS_31_SHAPE \
  { \
    1 \
  }
#define STAI_NETWORK_WEIGHTS_31_SCALE_OFFSET_NUM (0)
#define STAI_NETWORK_WEIGHTS_31_SCALES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_31_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_WEIGHTS_NUM (0)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_NETWORK_ACTIVATIONS_NUM (0)
#define STAI_NETWORK_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_NETWORK_ORIGIN_MODEL_NAME "rps_int8_OE_3_3_1"
#define STAI_NETWORK_C_MODEL_NAME "network"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_NETWORK_H
