#ifndef FIRMWARE_BUILD_VERSION_H
#define FIRMWARE_BUILD_VERSION_H

/* Generated by Tools/build_and_sign.ps1 before compiling all three images. */
#define NATI_LAB_FIRMWARE_VERSION       (5UL)
#define NATI_LAB_FIRMWARE_VERSION_TEXT  "5"

#endif /* FIRMWARE_BUILD_VERSION_H */