#ifndef FIRMWARE_BUILD_VERSION_H
#define FIRMWARE_BUILD_VERSION_H

/* Generated by an N6 build helper before compiling the Non-Secure image. */
#define NATI_LAB_FIRMWARE_VERSION       (4UL)
#define NATI_LAB_FIRMWARE_VERSION_TEXT  "4"

#endif /* FIRMWARE_BUILD_VERSION_H */