param(
    [ValidateRange(1, [uint32]::MaxValue)]
    [uint32]$FirmwareVersion = 1
)

$ErrorActionPreference = 'Stop'

$ProjectRoot = Split-Path -Parent $PSScriptRoot
. (Join-Path $PSScriptRoot 'N6-DevCommon.ps1')
$WorkspaceRoot = Split-Path -Parent $ProjectRoot
$IdeRoot = 'C:\ST\STM32CubeIDE_2.2.0\STM32CubeIDE'
$Builder = Join-Path $IdeRoot 'headless-build.bat'
$CubeProgrammerBin = Join-Path $IdeRoot 'plugins\com.st.stm32cube.ide.mcu.externaltools.cubeprogrammer.win32_2.2.500.202603051304\tools\bin'
$SigningTool = Join-Path $CubeProgrammerBin 'STM32_SigningTool_CLI.exe'
$Workspace = Join-Path $WorkspaceRoot '.codex-cubeide-workspace'
$OutputDir = Join-Path $ProjectRoot 'FlashImages'
$UsbPdCore = Join-Path $ProjectRoot 'AppliNonSecure\USBPD\App\usbpd_dpm_core.c'
$VersionHeader = Join-Path $ProjectRoot 'Common\Update\firmware_build_version.h'

$VersionHeaderText = @"
#ifndef FIRMWARE_BUILD_VERSION_H
#define FIRMWARE_BUILD_VERSION_H

/* Generated by Tools/build_and_sign.ps1 before compiling all three images. */
#define NATI_LAB_FIRMWARE_VERSION       (${FirmwareVersion}UL)
#define NATI_LAB_FIRMWARE_VERSION_TEXT  "$FirmwareVersion"

#endif /* FIRMWARE_BUILD_VERSION_H */
"@
[System.IO.File]::WriteAllText(
    $VersionHeader,
    $VersionHeaderText,
    [System.Text.UTF8Encoding]::new($false))

foreach ($required in @($Builder, $SigningTool)) {
    if (-not (Test-Path -LiteralPath $required)) {
        throw "Required ST tool was not found: $required"
    }
}

# CubeMX owns usbpd_dpm_core.c and silently restores the STM32N6 CAD task to
# 1 KiB on Generate Code.  That size is known to overflow in the TCPP0203
# initialization path.  Refuse to build/sign a regressed image.
if (-not (Select-String -LiteralPath $UsbPdCore `
        -Pattern '^#define\s+OS_CAD_STACK_SIZE\s+N6_USBPD_CAD_STACK_SIZE\s*$' `
        -Quiet)) {
    throw 'Unsafe USB-PD CAD stack: restore OS_CAD_STACK_SIZE to N6_USBPD_CAD_STACK_SIZE after CubeMX Generate Code.'
}

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

foreach ($configuration in @(
    'N6_FSBL/Debug',
    'N6_AppliSecure/Debug'
)) {
    & $Builder -data $Workspace -build $configuration
    if ($LASTEXITCODE -ne 0) {
        throw "Build failed: $configuration"
    }
}

# ux_user.h changes compile into the USBX middleware objects, but CubeIDE's
# linked-resource dependency tracking does not reliably invalidate them after
# CubeMX regeneration.  A clean Non-Secure build prevents stale USBX thread
# priorities, stack sizes, or feature switches from surviving into a signed
# image.
$nonSecureConfiguration = 'N6_AppliNonSecure/Debug'
& $Builder -data $Workspace -cleanBuild $nonSecureConfiguration
if ($LASTEXITCODE -ne 0) {
    throw "Clean build failed: $nonSecureConfiguration"
}

Assert-N6NonSecureImage -ProjectRoot $ProjectRoot

# The VL53L9 transform allocates about 356,688 bytes on its first frame before
# allocator metadata.  Fail the build before signing if linked code/static data
# leaves less than 360 KiB between _end and the reserved MSP stack.
$nonSecureMap = Join-Path $ProjectRoot 'AppliNonSecure\Debug\N6_AppliNonSecure.map'
$mapText = Get-Content -Raw -LiteralPath $nonSecureMap
$heapStartMatch = [regex]::Match(
    $mapText,
    '(?m)^\s*(0x[0-9a-fA-F]+)\s+PROVIDE \(_end = \.\)')
$heapLimitMatch = [regex]::Match(
    $mapText,
    '(?m)^\s*(0x[0-9a-fA-F]+)\s+_sstack = ')
if (-not $heapStartMatch.Success -or -not $heapLimitMatch.Success) {
    throw "Unable to determine the Non-Secure C heap capacity from: $nonSecureMap"
}
$heapStart = [Convert]::ToUInt64($heapStartMatch.Groups[1].Value.Substring(2), 16)
$heapLimit = [Convert]::ToUInt64($heapLimitMatch.Groups[1].Value.Substring(2), 16)
$availableHeapBytes = $heapLimit - $heapStart
$minimumTofHeapBytes = 360KB
if ($availableHeapBytes -lt $minimumTofHeapBytes) {
    throw "Insufficient Non-Secure C heap for VL53L9 transform: $availableHeapBytes bytes available, $minimumTofHeapBytes required."
}
Write-Host "Non-Secure C heap capacity: $availableHeapBytes bytes (minimum $minimumTofHeapBytes)."

$images = @(
    @{
        Input = Join-Path $ProjectRoot 'FSBL\Debug\N6_FSBL.bin'
        Output = Join-Path $OutputDir 'N6_FSBL-trusted.bin'
        Maximum = 0x00100000
    },
    @{
        Input = Join-Path $ProjectRoot 'AppliSecure\Debug\N6_AppliSecure.bin'
        Output = Join-Path $OutputDir 'N6_AppliSecure-trusted.bin'
        Maximum = 0x00080000
    },
    @{
        Input = Join-Path $ProjectRoot 'AppliNonSecure\Debug\N6_AppliNonSecure.bin'
        Output = Join-Path $OutputDir 'N6_AppliNonSecure-trusted.bin'
        Maximum = 0x000FFC00
    }
)

foreach ($image in $images) {
    $inputFile = Get-Item -LiteralPath $image.Input
    if ($inputFile.Length -gt $image.Maximum) {
        throw "Image exceeds its reserved region: $($inputFile.FullName)"
    }

    & $SigningTool -bin $image.Input -nk -of 0x80000000 -t fsbl `
        -o $image.Output -hv 2.3 -align -dump $image.Output -s
    if ($LASTEXITCODE -ne 0) {
        throw "Signing failed: $($image.Input)"
    }
}

& (Join-Path $PSScriptRoot 'New-FactoryBootMetadata.ps1') `
    -Output (Join-Path $OutputDir 'N6-BootMetadata.bin')
if ($LASTEXITCODE -ne 0) {
    throw 'Factory boot metadata generation failed.'
}

Write-Host "Build and signing completed. Images and factory metadata are in: $OutputDir"

$FirmwareKey = Join-Path $ProjectRoot '.local-dependencies\keys\firmware-update-p256-private.blob'
$FirmwarePackage = Join-Path $OutputDir ("N6-Firmware-v{0}.n6fw" -f $FirmwareVersion)
if (Test-Path -LiteralPath $FirmwareKey) {
    & (Join-Path $PSScriptRoot 'New-FirmwareUpdatePackage.ps1') `
        -Image (Join-Path $OutputDir 'N6_AppliNonSecure-trusted.bin') `
        -FirmwareVersion $FirmwareVersion `
        -Output $FirmwarePackage `
        -PrivateKeyPath $FirmwareKey
    if ($LASTEXITCODE -ne 0) {
        throw 'Firmware update package generation failed.'
    }
}
else {
    Write-Warning 'No private update-signing key was found; trusted images were built but no .n6fw package was created.'
    Write-Warning 'Run Tools\New-FirmwareSigningKey.ps1 once, protect the key, then rebuild.'
}
