param(
    [string]$PrivateKeyPath,
    [string]$PublicHeaderPath
)

$ErrorActionPreference = 'Stop'

$ProjectRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($PrivateKeyPath)) {
    $PrivateKeyPath = Join-Path $ProjectRoot '.local-dependencies\keys\firmware-update-p256-private.blob'
}
if ([string]::IsNullOrWhiteSpace($PublicHeaderPath)) {
    $PublicHeaderPath = Join-Path $ProjectRoot 'Common\Update\firmware_signing_public_key.h'
}

$privateDirectory = Split-Path -Parent $PrivateKeyPath
$publicDirectory = Split-Path -Parent $PublicHeaderPath
New-Item -ItemType Directory -Force -Path $privateDirectory | Out-Null
New-Item -ItemType Directory -Force -Path $publicDirectory | Out-Null

if (Test-Path -LiteralPath $PrivateKeyPath) {
    throw "Refusing to overwrite the existing private key: $PrivateKeyPath"
}

$ecdsa = New-Object System.Security.Cryptography.ECDsaCng(256)
$key = $ecdsa.Key

try {
    $parameters = $ecdsa.ExportParameters($false)
    $privateBlob = $key.Export(
        [System.Security.Cryptography.CngKeyBlobFormat]::EccPrivateBlob)
    [System.IO.File]::WriteAllBytes($PrivateKeyPath, $privateBlob)

    function Format-CBytes([byte[]]$Bytes) {
        $lines = @()
        for ($offset = 0; $offset -lt $Bytes.Length; $offset += 8) {
            $last = [Math]::Min($offset + 7, $Bytes.Length - 1)
            $values = $Bytes[$offset..$last] | ForEach-Object { '0x{0:X2}' -f $_ }
            $lines += '  ' + ($values -join ', ') + $(if ($last -lt ($Bytes.Length - 1)) { ',' } else { '' })
        }
        return $lines -join "`r`n"
    }

    $qx = Format-CBytes $parameters.Q.X
    $qy = Format-CBytes $parameters.Q.Y
    $header = @"
#ifndef FIRMWARE_SIGNING_PUBLIC_KEY_H
#define FIRMWARE_SIGNING_PUBLIC_KEY_H

#include <stdint.h>

/* Generated by Tools/New-FirmwareSigningKey.ps1.  The matching private key is
 * intentionally stored only under ignored .local-dependencies/keys. */
static const uint8_t FW_SIGNING_PUBLIC_KEY_X[32] =
{
$qx
};

static const uint8_t FW_SIGNING_PUBLIC_KEY_Y[32] =
{
$qy
};

#endif /* FIRMWARE_SIGNING_PUBLIC_KEY_H */
"@
    [System.IO.File]::WriteAllText($PublicHeaderPath, $header,
        [System.Text.UTF8Encoding]::new($false))
}
finally {
    $ecdsa.Dispose()
    $key.Dispose()
}

Write-Host "Private update-signing key created at: $PrivateKeyPath"
Write-Host "Public verification key created at: $PublicHeaderPath"
Write-Host 'Back up and protect the private key. Rebuild FSBL and Secure after changing it.'
