
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_rps_tof.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_RPS_TOF_H
#define __STAI_ATON_RPS_TOF_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_RPS_TOF_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_RPS_TOF_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_rps_tof_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_rps_tof_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_rps_tof_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_rps_tof_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_rps_tof_get_context_size(void)
{
  return STAI_RPS_TOF_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_rps_tof_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_rps_tof_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_rps_tof_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_rps_tof_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_rps_tof_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_rps_tof_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_rps_tof_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_rps_tof_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_rps_tof_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_rps_tof_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_rps_tof_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_rps_tof_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_rps_tof_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_rps_tof_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_rps_tof_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_rps_tof_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_rps_tof_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_rps_tof_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_rps_tof_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_rps_tof_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_rps_tof_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_rps_tof_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_rps_tof_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_rps_tof_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_RPS_TOF_STATES_NUM  (0)
#define STAI_RPS_TOF_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_RPS_TOF_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_RPS_TOF_IN_NUM (1)
#define STAI_RPS_TOF_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_RPS_TOF_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_RPS_TOF_IN_FORMATS \
  { \
    STAI_FORMAT_U8 \
  }
#define STAI_RPS_TOF_IN_SIZES \
  { \
    3200 \
  }
#define STAI_RPS_TOF_IN_SIZES_BYTES \
  { \
    3200 \
  }

#define STAI_RPS_TOF_IN_1_ALIGNMENT (32)
#define STAI_RPS_TOF_IN_1_NAME "Input_0_out_0"
#define STAI_RPS_TOF_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_IN_1_FORMAT (STAI_FORMAT_U8)
#define STAI_RPS_TOF_IN_1_SIZE (3200)
#define STAI_RPS_TOF_IN_1_SIZE_BYTES (3200)
#define STAI_RPS_TOF_IN_1_CHANNEL (1)
#define STAI_RPS_TOF_IN_1_HEIGHT (50)
#define STAI_RPS_TOF_IN_1_WIDTH (64)
#define STAI_RPS_TOF_IN_1_BATCH (1)
#define STAI_RPS_TOF_IN_1_RANK (4)
#define STAI_RPS_TOF_IN_1_SHAPE \
  { \
    1, 50, 64, 1 \
  }
#define STAI_RPS_TOF_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_IN_1_SCALES \
  { \
    1 \
  }
#define STAI_RPS_TOF_IN_1_OFFSETS \
  { \
    0 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_RPS_TOF_OUT_NUM (1)
#define STAI_RPS_TOF_OUT_ALIGNMENTS \
  { \
    16 \
  }
#define STAI_RPS_TOF_OUT_NAMES \
  { \
    "Quantize_37_out_0" \
  }
#define STAI_RPS_TOF_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_RPS_TOF_OUT_SIZES \
  { \
    4 \
  }
#define STAI_RPS_TOF_OUT_SIZES_BYTES \
  { \
    4 \
  }

#define STAI_RPS_TOF_OUT_1_ALIGNMENT (16)
#define STAI_RPS_TOF_OUT_1_NAME "Quantize_37_out_0"
#define STAI_RPS_TOF_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_RPS_TOF_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_OUT_1_SIZE (4)
#define STAI_RPS_TOF_OUT_1_SIZE_BYTES (4)
#define STAI_RPS_TOF_OUT_1_CHANNEL (1)
#define STAI_RPS_TOF_OUT_1_HEIGHT (1)
#define STAI_RPS_TOF_OUT_1_WIDTH (4)
#define STAI_RPS_TOF_OUT_1_RANK (2)
#define STAI_RPS_TOF_OUT_1_SHAPE \
  { \
    1, 4 \
  }
#define STAI_RPS_TOF_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_RPS_TOF_OUT_1_OFFSETS \
  { \
    -128 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_RPS_TOF_WEIGHTS_NUM (31)
#define STAI_RPS_TOF_WEIGHTS_ALIGNMENTS \
  { \
    16, 16, 16, 32, 32, 32, 32, 32, 32, 16, 16, 16, 32, 16, 16, 16, 32, 16, 16, 16, 32, 16, 16, 16, 16, 16, 32, 32, 32, 16, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_NAMES \
  { \
    "Quantize_3_y_scale", "Quantize_3_y_zero_point", "Conv2D_5_weights", "Conv2D_11_weights", "Conv2D_17_weights", "Conv2D_23_weights", "Gemm_29_weights_transposed_3", "Gemm_33_weights_transposed_9", "Conv2D_5_zero_off_14", "Conv2D_5_off_bias_20", "Conv2D_11_zero_off_23", "Conv2D_11_off_bias_29", "Conv2D_17_zero_off_32", "Conv2D_17_off_bias_38", "Conv2D_23_zero_off_41", "Conv2D_23_off_bias_47", "Gemm_29_conv_4_zero_off_50", "Gemm_29_conv_4_off_bias_56", "Gemm_33_conv_10_zero_off_59", "Gemm_33_conv_10_off_bias_65", "RequantizeLinear_inserted_id180_182_requantize_zero", "Conv2D_5_off_bias_18_A_16_184", "Conv2D_11_off_bias_27_A_16_186", "Conv2D_17_off_bias_36_A_16_188", "Conv2D_23_off_bias_45_A_16_190", "Gemm_29_conv_4_off_bias_54_A_16_192", "Gemm_33_conv_10_off_bias_63_A_16_194", "Gemm_33_squeeze_y_11_196_atonn_internal_scale", "Gemm_33_squeeze_y_11_196_atonn_internal_offset", "Softmax_36_200_atonn_internal_scale", "Softmax_36_200_atonn_internal_offset" \
  }
#define STAI_RPS_TOF_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_FLOAT32, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_Q7, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7 \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES \
  { \
    1, 1, 144, 4608, 13824, 27648, 2048, 128, 1, 16, 1, 32, 1, 48, 1, 64, 1, 32, 1, 4, 1, 16, 32, 48, 64, 32, 4, 1, 1, 1, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES_BYTES \
  { \
    4, 1, 144, 4608, 13824, 27648, 2048, 128, 1, 64, 1, 128, 1, 192, 1, 256, 1, 128, 1, 16, 1, 32, 64, 96, 128, 64, 8, 4, 1, 4, 1 \
  }

#define STAI_RPS_TOF_WEIGHTS_1_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_1_NAME "Quantize_3_y_scale"
#define STAI_RPS_TOF_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_1_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_1_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_1_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_1_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_1_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_1_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_1_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_1_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_1_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_1_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_1_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_2_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_2_NAME "Quantize_3_y_zero_point"
#define STAI_RPS_TOF_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_2_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_2_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_2_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_2_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_2_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_2_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_2_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_2_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_2_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_2_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_3_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_3_NAME "Conv2D_5_weights"
#define STAI_RPS_TOF_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_3_SIZE (144)
#define STAI_RPS_TOF_WEIGHTS_3_SIZE_BYTES (144)
#define STAI_RPS_TOF_WEIGHTS_3_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_3_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_3_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_3_BATCH (1)
#define STAI_RPS_TOF_WEIGHTS_3_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_3_SHAPE \
  { \
    16, 3, 3, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_3_SCALE_OFFSET_NUM (16)
#define STAI_RPS_TOF_WEIGHTS_3_SCALES \
  { \
    9.79889682639623e-06, 7.01733597452403e-06, 7.05212096363539e-06, 6.69391829433152e-06, 9.66095649346244e-06, 2.69488486992486e-06, 8.85190729604801e-06, 6.12914573139278e-06, 7.97398206486832e-06, 7.09228697814979e-06, 7.05725824445835e-06, 1.30091566461488e-05, 9.43261511565652e-06, 5.36210836799e-06, 7.33138313080417e-06, 8.98634698387468e-06 \
  }
#define STAI_RPS_TOF_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_4_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_4_NAME "Conv2D_11_weights"
#define STAI_RPS_TOF_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_4_SIZE (4608)
#define STAI_RPS_TOF_WEIGHTS_4_SIZE_BYTES (4608)
#define STAI_RPS_TOF_WEIGHTS_4_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_4_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_4_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_4_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_4_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_4_SHAPE \
  { \
    32, 2, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_4_SCALE_OFFSET_NUM (32)
#define STAI_RPS_TOF_WEIGHTS_4_SCALES \
  { \
    0.00169958791229874, 0.00138506840448827, 0.00159786164294928, 0.00135987473186105, 0.00159153575077653, 0.00182203820440918, 0.00139412807766348, 0.00204120413400233, 0.00135549646802247, 0.00160140765365213, 0.00173536909278482, 0.00154369266238064, 0.00209051347337663, 0.00186125177424401, 0.00213606678880751, 0.00200870959088206, 0.00166045152582228, 0.00170460052322596, 0.00163298938423395, 0.00219979719258845, 0.00157477054744959, 0.00195470242761075, 0.00183119566645473, 0.00160298275295645, 0.00175651488825679, 0.00181276677176356, 0.00157518615014851, 0.00234821997582912, 0.00195048388559371, 0.00173894083127379, 0.00178120110649616, 0.00159855326637626 \
  }
#define STAI_RPS_TOF_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_5_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_5_NAME "Conv2D_17_weights"
#define STAI_RPS_TOF_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_5_SIZE (13824)
#define STAI_RPS_TOF_WEIGHTS_5_SIZE_BYTES (13824)
#define STAI_RPS_TOF_WEIGHTS_5_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_5_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_5_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_5_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_5_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_5_SHAPE \
  { \
    48, 4, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_5_SCALE_OFFSET_NUM (48)
#define STAI_RPS_TOF_WEIGHTS_5_SCALES \
  { \
    0.00130205450113863, 0.00270087784156203, 0.00152656342834234, 0.0013612819602713, 0.0025316106621176, 0.00200129277072847, 0.00147430505603552, 0.00258073583245277, 0.00181765668094158, 0.00221387599594891, 0.00133094121702015, 0.00182407640386373, 0.00148056668695062, 0.00155518518295139, 0.00144732662010938, 0.00160630699247122, 0.0012096754508093, 0.00110901799052954, 0.00192634551785886, 0.00164438574574888, 0.00257752300240099, 0.00249013840220869, 0.00101373379584402, 0.00167856039479375, 0.00186409649904817, 0.00138002005405724, 0.00195030821487308, 0.00135667121503502, 0.00133644451852888, 0.00133283308241516, 0.00152811023872346, 0.0013128622667864, 0.00139620353002101, 0.00149710138794035, 0.00259842909872532, 0.00106794643215835, 0.00214545847848058, 0.0010245896410197, 0.00121985818259418, 0.00185640063136816, 0.00141527806408703, 0.00181418936699629, 0.00198841374367476, 0.0018158087041229, 0.00241025350987911, 0.00132301752455533, 0.00163409998640418, 0.00139812659472227 \
  }
#define STAI_RPS_TOF_WEIGHTS_5_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_6_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_6_NAME "Conv2D_23_weights"
#define STAI_RPS_TOF_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_6_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_6_SIZE (27648)
#define STAI_RPS_TOF_WEIGHTS_6_SIZE_BYTES (27648)
#define STAI_RPS_TOF_WEIGHTS_6_CHANNEL (48)
#define STAI_RPS_TOF_WEIGHTS_6_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_6_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_6_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_6_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_6_SHAPE \
  { \
    64, 6, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_6_SCALE_OFFSET_NUM (64)
#define STAI_RPS_TOF_WEIGHTS_6_SCALES \
  { \
    0.00160726509056985, 0.00117894075810909, 0.0024771720636636, 0.00125780119560659, 0.00128065573517233, 0.00199275440536439, 0.00228156615048647, 0.00163859128952026, 0.00252301967702806, 0.00106505851726979, 0.00137228809762746, 0.00259612663649023, 0.00135838089045137, 0.00166500464547426, 0.00201731594279408, 0.00202933233231306, 0.00107834360096604, 0.00184312416240573, 0.00102907815016806, 0.00123695842921734, 0.00144298444502056, 0.00234626000747085, 0.00159518851432949, 0.00235895463265479, 0.00311757274903357, 0.0011294805444777, 0.00125613331329077, 0.0010851708939299, 0.0029899796936661, 0.00127046904526651, 0.00199381005950272, 0.00136744615156204, 0.00167707074433565, 0.00143049983307719, 0.00117350474465638, 0.00116912228986621, 0.000966010498814285, 0.00194369757082313, 0.00231860182248056, 0.00100115046370775, 0.00263097998686135, 0.00118727178778499, 0.00208431691862643, 0.00115983781870455, 0.00275216833688319, 0.00119571597315371, 0.00298102735541761, 0.00078780367039144, 0.00199201074428856, 0.00217232317663729, 0.00128690025303513, 0.00227766018360853, 0.00178530800621957, 0.00302616646513343, 0.00126054661814123, 0.00140621652826667, 0.00129515072330832, 0.00139166659209877, 0.00304518919438124, 0.0021954367402941, 0.00163463910575956, 0.00254545034840703, 0.000739205395802855, 0.00158686027862132 \
  }
#define STAI_RPS_TOF_WEIGHTS_6_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_7_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_7_NAME "Gemm_29_weights_transposed_3"
#define STAI_RPS_TOF_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_7_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_7_SIZE (2048)
#define STAI_RPS_TOF_WEIGHTS_7_SIZE_BYTES (2048)
#define STAI_RPS_TOF_WEIGHTS_7_CHANNEL (64)
#define STAI_RPS_TOF_WEIGHTS_7_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_7_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_7_BATCH (64)
#define STAI_RPS_TOF_WEIGHTS_7_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_7_SHAPE \
  { \
    32, 1, 1, 64 \
  }
#define STAI_RPS_TOF_WEIGHTS_7_SCALE_OFFSET_NUM (32)
#define STAI_RPS_TOF_WEIGHTS_7_SCALES \
  { \
    0.0029385513626039, 0.00194528070278466, 0.00200469326227903, 0.0020793576259166, 0.00249800970777869, 0.0025266835000366, 0.0031355565879494, 0.00189876253716648, 0.00236621289514005, 0.00252460478805006, 0.00214343541301787, 0.00275795417837799, 0.00196615909226239, 0.00276343431323767, 0.00299667636863887, 0.00253191660158336, 0.00195991992950439, 0.00209508556872606, 0.0026963734999299, 0.00277302018366754, 0.00196092133410275, 0.00208901730366051, 0.00292679271660745, 0.00229238229803741, 0.00228838482871652, 0.00181372091174126, 0.00271964585408568, 0.00280558504164219, 0.0028201756067574, 0.00263016927056015, 0.00196490972302854, 0.00251677189953625 \
  }
#define STAI_RPS_TOF_WEIGHTS_7_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_8_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_8_NAME "Gemm_33_weights_transposed_9"
#define STAI_RPS_TOF_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_8_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_8_SIZE (128)
#define STAI_RPS_TOF_WEIGHTS_8_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_8_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_8_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_8_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_8_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_8_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_8_SHAPE \
  { \
    4, 1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_8_SCALE_OFFSET_NUM (4)
#define STAI_RPS_TOF_WEIGHTS_8_SCALES \
  { \
    0.00398380309343338, 0.0032601656857878, 0.00327973160892725, 0.00376794254407287 \
  }
#define STAI_RPS_TOF_WEIGHTS_8_OFFSETS \
  { \
    0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_9_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_9_NAME "Conv2D_5_zero_off_14"
#define STAI_RPS_TOF_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_9_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_9_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_9_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_9_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_9_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_9_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_9_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_9_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_9_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_9_SCALES \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_9_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_10_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_10_NAME "Conv2D_5_off_bias_20"
#define STAI_RPS_TOF_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_10_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_10_SIZE (16)
#define STAI_RPS_TOF_WEIGHTS_10_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_10_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_10_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_10_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_10_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_10_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_10_SHAPE \
  { \
    2, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_10_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_10_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_10_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_11_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_11_NAME "Conv2D_11_zero_off_23"
#define STAI_RPS_TOF_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_11_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_11_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_11_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_11_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_11_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_11_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_11_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_11_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_11_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_11_SCALES \
  { \
    0.00571833178400993 \
  }
#define STAI_RPS_TOF_WEIGHTS_11_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_12_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_12_NAME "Conv2D_11_off_bias_29"
#define STAI_RPS_TOF_WEIGHTS_12_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_12_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_12_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_12_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_12_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_12_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_12_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_12_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_12_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_12_SHAPE \
  { \
    4, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_12_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_12_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_12_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_13_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_13_NAME "Conv2D_17_zero_off_32"
#define STAI_RPS_TOF_WEIGHTS_13_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_13_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_13_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_13_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_13_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_13_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_13_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_13_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_13_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_13_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_13_SCALES \
  { \
    0.0166669394820929 \
  }
#define STAI_RPS_TOF_WEIGHTS_13_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_14_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_14_NAME "Conv2D_17_off_bias_38"
#define STAI_RPS_TOF_WEIGHTS_14_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_14_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_14_SIZE (48)
#define STAI_RPS_TOF_WEIGHTS_14_SIZE_BYTES (192)
#define STAI_RPS_TOF_WEIGHTS_14_CHANNEL (48)
#define STAI_RPS_TOF_WEIGHTS_14_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_14_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_14_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_14_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_14_SHAPE \
  { \
    6, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_14_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_14_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_14_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_15_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_15_NAME "Conv2D_23_zero_off_41"
#define STAI_RPS_TOF_WEIGHTS_15_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_15_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_15_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_15_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_15_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_15_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_15_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_15_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_15_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_15_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_15_SCALES \
  { \
    0.0336679629981518 \
  }
#define STAI_RPS_TOF_WEIGHTS_15_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_16_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_16_NAME "Conv2D_23_off_bias_47"
#define STAI_RPS_TOF_WEIGHTS_16_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_16_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_16_SIZE (64)
#define STAI_RPS_TOF_WEIGHTS_16_SIZE_BYTES (256)
#define STAI_RPS_TOF_WEIGHTS_16_CHANNEL (64)
#define STAI_RPS_TOF_WEIGHTS_16_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_16_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_16_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_16_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_16_SHAPE \
  { \
    8, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_16_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_16_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_16_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_17_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_17_NAME "Gemm_29_conv_4_zero_off_50"
#define STAI_RPS_TOF_WEIGHTS_17_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_17_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_17_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_17_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_17_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_17_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_17_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_17_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_17_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_17_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_17_SCALES \
  { \
    0.0457772314548492 \
  }
#define STAI_RPS_TOF_WEIGHTS_17_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_18_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_18_NAME "Gemm_29_conv_4_off_bias_56"
#define STAI_RPS_TOF_WEIGHTS_18_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_18_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_18_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_18_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_18_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_18_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_18_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_18_BATCH (16)
#define STAI_RPS_TOF_WEIGHTS_18_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_18_SHAPE \
  { \
    2, 1, 1, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_18_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_18_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_18_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_19_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_19_NAME "Gemm_33_conv_10_zero_off_59"
#define STAI_RPS_TOF_WEIGHTS_19_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_19_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_19_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_19_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_19_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_19_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_19_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_19_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_19_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_19_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_19_SCALES \
  { \
    0.0670357868075371 \
  }
#define STAI_RPS_TOF_WEIGHTS_19_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_20_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_20_NAME "Gemm_33_conv_10_off_bias_65"
#define STAI_RPS_TOF_WEIGHTS_20_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_20_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_20_SIZE (4)
#define STAI_RPS_TOF_WEIGHTS_20_SIZE_BYTES (16)
#define STAI_RPS_TOF_WEIGHTS_20_CHANNEL (4)
#define STAI_RPS_TOF_WEIGHTS_20_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_20_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_20_BATCH (4)
#define STAI_RPS_TOF_WEIGHTS_20_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_20_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_RPS_TOF_WEIGHTS_20_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_20_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_20_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_21_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_21_NAME "RequantizeLinear_inserted_id180_182_requantize_zero"
#define STAI_RPS_TOF_WEIGHTS_21_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_21_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_21_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_21_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_21_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_21_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_21_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_21_BATCH (1)
#define STAI_RPS_TOF_WEIGHTS_21_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_21_SHAPE \
  { \
    1, 1, 1, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_21_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_21_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_21_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_22_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_22_NAME "Conv2D_5_off_bias_18_A_16_184"
#define STAI_RPS_TOF_WEIGHTS_22_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_22_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_22_SIZE (16)
#define STAI_RPS_TOF_WEIGHTS_22_SIZE_BYTES (32)
#define STAI_RPS_TOF_WEIGHTS_22_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_22_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_22_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_22_BATCH (16)
#define STAI_RPS_TOF_WEIGHTS_22_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_22_SHAPE \
  { \
    1, 1, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_22_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_22_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_22_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_23_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_23_NAME "Conv2D_11_off_bias_27_A_16_186"
#define STAI_RPS_TOF_WEIGHTS_23_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_23_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_23_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_23_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_23_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_23_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_23_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_23_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_23_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_23_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_23_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_23_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_23_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_24_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_24_NAME "Conv2D_17_off_bias_36_A_16_188"
#define STAI_RPS_TOF_WEIGHTS_24_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_24_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_24_SIZE (48)
#define STAI_RPS_TOF_WEIGHTS_24_SIZE_BYTES (96)
#define STAI_RPS_TOF_WEIGHTS_24_CHANNEL (48)
#define STAI_RPS_TOF_WEIGHTS_24_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_24_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_24_BATCH (48)
#define STAI_RPS_TOF_WEIGHTS_24_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_24_SHAPE \
  { \
    1, 1, 48 \
  }
#define STAI_RPS_TOF_WEIGHTS_24_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_24_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_24_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_25_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_25_NAME "Conv2D_23_off_bias_45_A_16_190"
#define STAI_RPS_TOF_WEIGHTS_25_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_25_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_25_SIZE (64)
#define STAI_RPS_TOF_WEIGHTS_25_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_25_CHANNEL (64)
#define STAI_RPS_TOF_WEIGHTS_25_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_25_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_25_BATCH (64)
#define STAI_RPS_TOF_WEIGHTS_25_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_25_SHAPE \
  { \
    1, 1, 64 \
  }
#define STAI_RPS_TOF_WEIGHTS_25_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_25_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_25_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_26_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_26_NAME "Gemm_29_conv_4_off_bias_54_A_16_192"
#define STAI_RPS_TOF_WEIGHTS_26_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_26_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_26_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_26_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_26_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_26_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_26_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_26_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_26_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_26_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_26_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_26_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_26_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_27_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_27_NAME "Gemm_33_conv_10_off_bias_63_A_16_194"
#define STAI_RPS_TOF_WEIGHTS_27_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_27_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_27_SIZE (4)
#define STAI_RPS_TOF_WEIGHTS_27_SIZE_BYTES (8)
#define STAI_RPS_TOF_WEIGHTS_27_CHANNEL (4)
#define STAI_RPS_TOF_WEIGHTS_27_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_27_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_27_BATCH (4)
#define STAI_RPS_TOF_WEIGHTS_27_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_27_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_RPS_TOF_WEIGHTS_27_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_27_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_27_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_28_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_28_NAME "Gemm_33_squeeze_y_11_196_atonn_internal_scale"
#define STAI_RPS_TOF_WEIGHTS_28_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_28_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_28_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_28_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_28_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_28_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_28_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_28_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_28_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_28_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_28_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_28_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_29_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_29_NAME "Gemm_33_squeeze_y_11_196_atonn_internal_offset"
#define STAI_RPS_TOF_WEIGHTS_29_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_29_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_29_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_29_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_29_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_29_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_29_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_29_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_29_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_29_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_29_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_29_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_30_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_30_NAME "Softmax_36_200_atonn_internal_scale"
#define STAI_RPS_TOF_WEIGHTS_30_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_30_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_30_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_30_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_30_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_30_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_30_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_30_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_30_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_30_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_30_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_30_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_31_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_31_NAME "Softmax_36_200_atonn_internal_offset"
#define STAI_RPS_TOF_WEIGHTS_31_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_31_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_31_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_31_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_31_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_31_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_31_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_31_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_31_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_31_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_31_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_31_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_RPS_TOF_WEIGHTS_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_NAMES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_FORMATS \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_RPS_TOF_ACTIVATIONS_NUM (0)
#define STAI_RPS_TOF_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_RPS_TOF_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_RPS_TOF_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_RPS_TOF_ORIGIN_MODEL_NAME "rps_int8_OE_3_3_1"
#define STAI_RPS_TOF_C_MODEL_NAME "rps_tof"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_RPS_TOF_H
