
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_rps_tof.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_RPS_TOF_H
#define __STAI_ATON_RPS_TOF_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_RPS_TOF_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_RPS_TOF_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_rps_tof_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_rps_tof_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_rps_tof_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_rps_tof_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_rps_tof_get_context_size(void)
{
  return STAI_RPS_TOF_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_rps_tof_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_rps_tof_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_rps_tof_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_rps_tof_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_rps_tof_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_rps_tof_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_rps_tof_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_rps_tof_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_rps_tof_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_rps_tof_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_rps_tof_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_rps_tof_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_rps_tof_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_rps_tof_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_rps_tof_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_rps_tof_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_rps_tof_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_rps_tof_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_rps_tof_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_rps_tof_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_rps_tof_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_rps_tof_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_rps_tof_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_rps_tof_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_RPS_TOF_STATES_NUM  (0)
#define STAI_RPS_TOF_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_RPS_TOF_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_RPS_TOF_IN_NUM (1)
#define STAI_RPS_TOF_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_RPS_TOF_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_RPS_TOF_IN_FORMATS \
  { \
    STAI_FORMAT_U8 \
  }
#define STAI_RPS_TOF_IN_SIZES \
  { \
    3200 \
  }
#define STAI_RPS_TOF_IN_SIZES_BYTES \
  { \
    3200 \
  }

#define STAI_RPS_TOF_IN_1_ALIGNMENT (32)
#define STAI_RPS_TOF_IN_1_NAME "Input_0_out_0"
#define STAI_RPS_TOF_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_IN_1_FORMAT (STAI_FORMAT_U8)
#define STAI_RPS_TOF_IN_1_SIZE (3200)
#define STAI_RPS_TOF_IN_1_SIZE_BYTES (3200)
#define STAI_RPS_TOF_IN_1_CHANNEL (1)
#define STAI_RPS_TOF_IN_1_HEIGHT (50)
#define STAI_RPS_TOF_IN_1_WIDTH (64)
#define STAI_RPS_TOF_IN_1_BATCH (1)
#define STAI_RPS_TOF_IN_1_RANK (4)
#define STAI_RPS_TOF_IN_1_SHAPE \
  { \
    1, 50, 64, 1 \
  }
#define STAI_RPS_TOF_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_IN_1_SCALES \
  { \
    1 \
  }
#define STAI_RPS_TOF_IN_1_OFFSETS \
  { \
    0 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_RPS_TOF_OUT_NUM (1)
#define STAI_RPS_TOF_OUT_ALIGNMENTS \
  { \
    16 \
  }
#define STAI_RPS_TOF_OUT_NAMES \
  { \
    "Quantize_39_out_0" \
  }
#define STAI_RPS_TOF_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_RPS_TOF_OUT_SIZES \
  { \
    4 \
  }
#define STAI_RPS_TOF_OUT_SIZES_BYTES \
  { \
    4 \
  }

#define STAI_RPS_TOF_OUT_1_ALIGNMENT (16)
#define STAI_RPS_TOF_OUT_1_NAME "Quantize_39_out_0"
#define STAI_RPS_TOF_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_RPS_TOF_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_OUT_1_SIZE (4)
#define STAI_RPS_TOF_OUT_1_SIZE_BYTES (4)
#define STAI_RPS_TOF_OUT_1_CHANNEL (1)
#define STAI_RPS_TOF_OUT_1_HEIGHT (1)
#define STAI_RPS_TOF_OUT_1_WIDTH (4)
#define STAI_RPS_TOF_OUT_1_RANK (2)
#define STAI_RPS_TOF_OUT_1_SHAPE \
  { \
    1, 4 \
  }
#define STAI_RPS_TOF_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_RPS_TOF_OUT_1_OFFSETS \
  { \
    -128 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_RPS_TOF_WEIGHTS_NUM (29)
#define STAI_RPS_TOF_WEIGHTS_ALIGNMENTS \
  { \
    32, 32, 32, 32, 32, 16, 32, 32, 16, 32, 32, 32, 16, 32, 32, 32, 16, 32, 32, 32, 32, 32, 16, 32, 16, 32, 16, 16, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_NAMES \
  { \
    "Conv2D_7_weights", "Conv2D_13_weights", "Conv2D_19_weights", "Conv2D_25_weights", "Gemm_31_weights_transposed_3", "Gemm_35_weights_transposed_9", "Conv2D_7_zero_off_14", "Conv2D_7_off_bias_20", "Conv2D_13_zero_off_23", "Conv2D_13_off_bias_29", "Conv2D_19_zero_off_32", "Conv2D_19_off_bias_38", "Conv2D_25_zero_off_41", "Conv2D_25_off_bias_47", "Gemm_31_conv_4_zero_off_50", "Gemm_31_conv_4_off_bias_56", "Gemm_35_conv_10_zero_off_59", "Gemm_35_conv_10_off_bias_65", "Quantize_5_172_requantize_zero", "Conv2D_7_off_bias_18_A_16_190", "Conv2D_13_off_bias_27_A_16_192", "Conv2D_19_off_bias_36_A_16_194", "Conv2D_25_off_bias_45_A_16_196", "Gemm_31_conv_4_off_bias_54_A_16_198", "Gemm_35_conv_10_off_bias_63_A_16_200", "Gemm_35_squeeze_y_11_202_atonn_internal_scale", "Gemm_35_squeeze_y_11_202_atonn_internal_offset", "Softmax_38_206_atonn_internal_scale", "Softmax_38_206_atonn_internal_offset" \
  }
#define STAI_RPS_TOF_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_Q7, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7 \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES \
  { \
    144, 3456, 6912, 6912, 36864, 128, 1, 16, 1, 24, 1, 32, 1, 24, 1, 32, 1, 4, 1, 16, 24, 32, 24, 32, 4, 1, 1, 1, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES_BYTES \
  { \
    144, 3456, 6912, 6912, 36864, 128, 1, 64, 1, 96, 1, 128, 1, 96, 1, 128, 1, 16, 1, 32, 48, 64, 48, 64, 8, 4, 1, 4, 1 \
  }

#define STAI_RPS_TOF_WEIGHTS_1_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_1_NAME "Conv2D_7_weights"
#define STAI_RPS_TOF_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_1_SIZE (144)
#define STAI_RPS_TOF_WEIGHTS_1_SIZE_BYTES (144)
#define STAI_RPS_TOF_WEIGHTS_1_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_1_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_1_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_1_BATCH (1)
#define STAI_RPS_TOF_WEIGHTS_1_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_1_SHAPE \
  { \
    16, 3, 3, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_1_SCALE_OFFSET_NUM (16)
#define STAI_RPS_TOF_WEIGHTS_1_SCALES \
  { \
    6.19206775809289e-06, 6.69860810376122e-06, 6.52001426715287e-06, 5.53761674382258e-06, 6.30023032499594e-06, 6.05353397986619e-06, 5.96955987930414e-06, 4.87422994410736e-06, 5.81423819312477e-06, 5.23625976711628e-06, 5.7645729611977e-06, 5.85886982662487e-06, 6.14679402133333e-06, 5.47569879927323e-06, 6.58661019770079e-06, 4.73606223749812e-06 \
  }
#define STAI_RPS_TOF_WEIGHTS_1_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_2_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_2_NAME "Conv2D_13_weights"
#define STAI_RPS_TOF_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_2_SIZE (3456)
#define STAI_RPS_TOF_WEIGHTS_2_SIZE_BYTES (3456)
#define STAI_RPS_TOF_WEIGHTS_2_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_2_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_2_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_2_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_2_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_2_SHAPE \
  { \
    24, 2, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_2_SCALE_OFFSET_NUM (24)
#define STAI_RPS_TOF_WEIGHTS_2_SCALES \
  { \
    0.00119129254017025, 0.00109789578709751, 0.00112877786159515, 0.00117874448187649, 0.0011576620163396, 0.00108905998058617, 0.00110998377203941, 0.00118923699483275, 0.00115329842083156, 0.00119886815082282, 0.001096400199458, 0.0011490904726088, 0.00124423683155328, 0.00116815906949341, 0.00126695015933365, 0.00118128850590438, 0.00125688163097948, 0.00113037356641144, 0.00127252796664834, 0.00110011920332909, 0.00114298530388623, 0.00116598571185023, 0.00117305864114314, 0.00106771243736148 \
  }
#define STAI_RPS_TOF_WEIGHTS_2_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_3_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_3_NAME "Conv2D_19_weights"
#define STAI_RPS_TOF_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_3_SIZE (6912)
#define STAI_RPS_TOF_WEIGHTS_3_SIZE_BYTES (6912)
#define STAI_RPS_TOF_WEIGHTS_3_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_3_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_3_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_3_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_3_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_3_SHAPE \
  { \
    32, 3, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_3_SCALE_OFFSET_NUM (32)
#define STAI_RPS_TOF_WEIGHTS_3_SCALES \
  { \
    0.000937347766011953, 0.00102431606501341, 0.00106294627767056, 0.00115803512744606, 0.00094324053497985, 0.00094816874479875, 0.00109265209175646, 0.000970343069639057, 0.000995548325590789, 0.00110492436215281, 0.000962572637945414, 0.00111635506618768, 0.00108942855149508, 0.00102914462331682, 0.00102190487086773, 0.00095699995290488, 0.00108210311736912, 0.00094706699019298, 0.00103967206086963, 0.00106013228651136, 0.000991449924185872, 0.000996055547147989, 0.00108375551644713, 0.00108598591759801, 0.000996357412077487, 0.00106179900467396, 0.00105377321597189, 0.00104446895420551, 0.00103757169563323, 0.000960093049798161, 0.00104205228853971, 0.000961924612056464 \
  }
#define STAI_RPS_TOF_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_4_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_4_NAME "Conv2D_25_weights"
#define STAI_RPS_TOF_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_4_SIZE (6912)
#define STAI_RPS_TOF_WEIGHTS_4_SIZE_BYTES (6912)
#define STAI_RPS_TOF_WEIGHTS_4_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_4_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_4_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_4_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_4_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_4_SHAPE \
  { \
    24, 4, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_4_SCALE_OFFSET_NUM (24)
#define STAI_RPS_TOF_WEIGHTS_4_SCALES \
  { \
    0.000992360175587237, 0.0011953596258536, 0.000967356376349926, 0.000967750384006649, 0.00106482091359794, 0.0010791311506182, 0.00105909339617938, 0.00112365570385009, 0.00105456355959177, 0.000973418063949794, 0.00105121778324246, 0.00104946573264897, 0.00102694076485932, 0.000974519120063633, 0.000925736618228257, 0.00105778069701046, 0.00110671925358474, 0.000986928818747401, 0.000958020391408354, 0.00096477079205215, 0.00102172850165516, 0.00109435990452766, 0.00100010796450078, 0.00101649214047939 \
  }
#define STAI_RPS_TOF_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_5_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_5_NAME "Gemm_31_weights_transposed_3"
#define STAI_RPS_TOF_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_5_SIZE (36864)
#define STAI_RPS_TOF_WEIGHTS_5_SIZE_BYTES (36864)
#define STAI_RPS_TOF_WEIGHTS_5_CHANNEL (1152)
#define STAI_RPS_TOF_WEIGHTS_5_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_5_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_5_BATCH (128)
#define STAI_RPS_TOF_WEIGHTS_5_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_5_SHAPE \
  { \
    32, 9, 1, 1, 128 \
  }
#define STAI_RPS_TOF_WEIGHTS_5_SCALE_OFFSET_NUM (32)
#define STAI_RPS_TOF_WEIGHTS_5_SCALES \
  { \
    0.000818556000012904, 0.000841275439597666, 0.00061124621424824, 0.000604641798418015, 0.000839795975480229, 0.000886579917278141, 0.000882287160493433, 0.00060298532480374, 0.000629070971626788, 0.000607084133662283, 0.000796349544543773, 0.000943147751968354, 0.000618779158685356, 0.000849641801323742, 0.000626893539447337, 0.000560393440537155, 0.000779906695242971, 0.000618855934590101, 0.000948884524405003, 0.000614014104939997, 0.000848953903187066, 0.000643142207991332, 0.000634799303952605, 0.000935349729843438, 0.000920540071092546, 0.000630676164291799, 0.000690976448822767, 0.000768800382502377, 0.00077102443901822, 0.000606939429417253, 0.000626954599283636, 0.000636883603874594 \
  }
#define STAI_RPS_TOF_WEIGHTS_5_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_6_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_6_NAME "Gemm_35_weights_transposed_9"
#define STAI_RPS_TOF_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_6_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_6_SIZE (128)
#define STAI_RPS_TOF_WEIGHTS_6_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_6_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_6_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_6_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_6_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_6_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_6_SHAPE \
  { \
    4, 1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_6_SCALE_OFFSET_NUM (4)
#define STAI_RPS_TOF_WEIGHTS_6_SCALES \
  { \
    0.00313156121410429, 0.00296783517114818, 0.00321494624949992, 0.00314419995993376 \
  }
#define STAI_RPS_TOF_WEIGHTS_6_OFFSETS \
  { \
    0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_7_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_7_NAME "Conv2D_7_zero_off_14"
#define STAI_RPS_TOF_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_7_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_7_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_7_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_7_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_7_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_7_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_7_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_7_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_7_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_7_SCALES \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_7_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_8_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_8_NAME "Conv2D_7_off_bias_20"
#define STAI_RPS_TOF_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_8_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_8_SIZE (16)
#define STAI_RPS_TOF_WEIGHTS_8_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_8_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_8_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_8_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_8_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_8_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_8_SHAPE \
  { \
    2, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_8_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_8_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_8_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_9_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_9_NAME "Conv2D_13_zero_off_23"
#define STAI_RPS_TOF_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_9_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_9_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_9_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_9_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_9_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_9_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_9_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_9_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_9_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_9_SCALES \
  { \
    0.00335614779032767 \
  }
#define STAI_RPS_TOF_WEIGHTS_9_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_10_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_10_NAME "Conv2D_13_off_bias_29"
#define STAI_RPS_TOF_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_10_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_10_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_10_SIZE_BYTES (96)
#define STAI_RPS_TOF_WEIGHTS_10_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_10_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_10_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_10_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_10_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_10_SHAPE \
  { \
    3, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_10_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_10_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_10_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_11_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_11_NAME "Conv2D_19_zero_off_32"
#define STAI_RPS_TOF_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_11_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_11_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_11_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_11_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_11_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_11_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_11_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_11_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_11_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_11_SCALES \
  { \
    0.00505426293238997 \
  }
#define STAI_RPS_TOF_WEIGHTS_11_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_12_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_12_NAME "Conv2D_19_off_bias_38"
#define STAI_RPS_TOF_WEIGHTS_12_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_12_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_12_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_12_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_12_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_12_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_12_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_12_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_12_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_12_SHAPE \
  { \
    4, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_12_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_12_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_12_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_13_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_13_NAME "Conv2D_25_zero_off_41"
#define STAI_RPS_TOF_WEIGHTS_13_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_13_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_13_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_13_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_13_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_13_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_13_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_13_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_13_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_13_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_13_SCALES \
  { \
    0.00970660615712404 \
  }
#define STAI_RPS_TOF_WEIGHTS_13_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_14_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_14_NAME "Conv2D_25_off_bias_47"
#define STAI_RPS_TOF_WEIGHTS_14_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_14_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_14_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_14_SIZE_BYTES (96)
#define STAI_RPS_TOF_WEIGHTS_14_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_14_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_14_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_14_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_14_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_14_SHAPE \
  { \
    3, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_14_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_14_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_14_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_15_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_15_NAME "Gemm_31_conv_4_zero_off_50"
#define STAI_RPS_TOF_WEIGHTS_15_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_15_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_15_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_15_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_15_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_15_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_15_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_15_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_15_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_15_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_15_SCALES \
  { \
    0.016063004732132 \
  }
#define STAI_RPS_TOF_WEIGHTS_15_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_16_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_16_NAME "Gemm_31_conv_4_off_bias_56"
#define STAI_RPS_TOF_WEIGHTS_16_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_16_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_16_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_16_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_16_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_16_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_16_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_16_BATCH (16)
#define STAI_RPS_TOF_WEIGHTS_16_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_16_SHAPE \
  { \
    2, 1, 1, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_16_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_16_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_16_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_17_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_17_NAME "Gemm_35_conv_10_zero_off_59"
#define STAI_RPS_TOF_WEIGHTS_17_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_17_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_17_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_17_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_17_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_17_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_17_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_17_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_17_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_17_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_17_SCALES \
  { \
    0.0607886537909508 \
  }
#define STAI_RPS_TOF_WEIGHTS_17_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_18_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_18_NAME "Gemm_35_conv_10_off_bias_65"
#define STAI_RPS_TOF_WEIGHTS_18_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_18_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_18_SIZE (4)
#define STAI_RPS_TOF_WEIGHTS_18_SIZE_BYTES (16)
#define STAI_RPS_TOF_WEIGHTS_18_CHANNEL (4)
#define STAI_RPS_TOF_WEIGHTS_18_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_18_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_18_BATCH (4)
#define STAI_RPS_TOF_WEIGHTS_18_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_18_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_RPS_TOF_WEIGHTS_18_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_18_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_18_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_19_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_19_NAME "Quantize_5_172_requantize_zero"
#define STAI_RPS_TOF_WEIGHTS_19_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_19_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_19_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_19_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_19_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_19_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_19_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_19_BATCH (1)
#define STAI_RPS_TOF_WEIGHTS_19_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_19_SHAPE \
  { \
    1, 1, 1, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_19_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_19_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_19_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_20_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_20_NAME "Conv2D_7_off_bias_18_A_16_190"
#define STAI_RPS_TOF_WEIGHTS_20_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_20_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_20_SIZE (16)
#define STAI_RPS_TOF_WEIGHTS_20_SIZE_BYTES (32)
#define STAI_RPS_TOF_WEIGHTS_20_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_20_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_20_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_20_BATCH (16)
#define STAI_RPS_TOF_WEIGHTS_20_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_20_SHAPE \
  { \
    1, 1, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_20_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_20_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_20_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_21_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_21_NAME "Conv2D_13_off_bias_27_A_16_192"
#define STAI_RPS_TOF_WEIGHTS_21_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_21_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_21_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_21_SIZE_BYTES (48)
#define STAI_RPS_TOF_WEIGHTS_21_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_21_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_21_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_21_BATCH (24)
#define STAI_RPS_TOF_WEIGHTS_21_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_21_SHAPE \
  { \
    1, 1, 24 \
  }
#define STAI_RPS_TOF_WEIGHTS_21_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_21_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_21_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_22_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_22_NAME "Conv2D_19_off_bias_36_A_16_194"
#define STAI_RPS_TOF_WEIGHTS_22_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_22_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_22_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_22_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_22_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_22_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_22_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_22_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_22_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_22_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_22_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_22_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_22_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_23_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_23_NAME "Conv2D_25_off_bias_45_A_16_196"
#define STAI_RPS_TOF_WEIGHTS_23_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_23_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_23_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_23_SIZE_BYTES (48)
#define STAI_RPS_TOF_WEIGHTS_23_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_23_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_23_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_23_BATCH (24)
#define STAI_RPS_TOF_WEIGHTS_23_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_23_SHAPE \
  { \
    1, 1, 24 \
  }
#define STAI_RPS_TOF_WEIGHTS_23_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_23_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_23_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_24_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_24_NAME "Gemm_31_conv_4_off_bias_54_A_16_198"
#define STAI_RPS_TOF_WEIGHTS_24_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_24_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_24_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_24_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_24_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_24_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_24_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_24_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_24_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_24_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_24_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_24_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_24_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_25_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_25_NAME "Gemm_35_conv_10_off_bias_63_A_16_200"
#define STAI_RPS_TOF_WEIGHTS_25_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_25_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_25_SIZE (4)
#define STAI_RPS_TOF_WEIGHTS_25_SIZE_BYTES (8)
#define STAI_RPS_TOF_WEIGHTS_25_CHANNEL (4)
#define STAI_RPS_TOF_WEIGHTS_25_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_25_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_25_BATCH (4)
#define STAI_RPS_TOF_WEIGHTS_25_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_25_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_RPS_TOF_WEIGHTS_25_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_25_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_25_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_26_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_26_NAME "Gemm_35_squeeze_y_11_202_atonn_internal_scale"
#define STAI_RPS_TOF_WEIGHTS_26_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_26_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_26_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_26_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_26_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_26_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_26_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_26_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_26_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_26_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_26_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_26_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_27_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_27_NAME "Gemm_35_squeeze_y_11_202_atonn_internal_offset"
#define STAI_RPS_TOF_WEIGHTS_27_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_27_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_27_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_27_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_27_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_27_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_27_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_27_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_27_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_27_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_27_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_27_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_28_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_28_NAME "Softmax_38_206_atonn_internal_scale"
#define STAI_RPS_TOF_WEIGHTS_28_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_28_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_28_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_28_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_28_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_28_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_28_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_28_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_28_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_28_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_28_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_28_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_29_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_29_NAME "Softmax_38_206_atonn_internal_offset"
#define STAI_RPS_TOF_WEIGHTS_29_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_29_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_29_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_29_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_29_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_29_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_29_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_29_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_29_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_29_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_29_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_29_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_RPS_TOF_WEIGHTS_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_NAMES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_FORMATS \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_RPS_TOF_ACTIVATIONS_NUM (0)
#define STAI_RPS_TOF_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_RPS_TOF_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_RPS_TOF_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_RPS_TOF_ORIGIN_MODEL_NAME "rps_int8_OE_3_3_1"
#define STAI_RPS_TOF_C_MODEL_NAME "rps_tof"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_RPS_TOF_H
