
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_rps_tof.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_RPS_TOF_H
#define __STAI_ATON_RPS_TOF_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_RPS_TOF_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_RPS_TOF_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_rps_tof_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_rps_tof_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_rps_tof_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_rps_tof_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_rps_tof_get_context_size(void)
{
  return STAI_RPS_TOF_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_rps_tof_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_rps_tof_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_rps_tof_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_rps_tof_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_rps_tof_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_rps_tof_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_rps_tof_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_rps_tof_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_rps_tof_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_rps_tof_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_rps_tof_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_rps_tof_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_rps_tof_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_rps_tof_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_rps_tof_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_rps_tof_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_rps_tof_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_rps_tof_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_rps_tof_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_rps_tof_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_rps_tof_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_rps_tof_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_rps_tof_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_rps_tof_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_rps_tof_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_rps_tof_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_rps_tof_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_RPS_TOF_STATES_NUM  (0)
#define STAI_RPS_TOF_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_RPS_TOF_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_RPS_TOF_IN_NUM (1)
#define STAI_RPS_TOF_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_RPS_TOF_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_RPS_TOF_IN_FORMATS \
  { \
    STAI_FORMAT_U8 \
  }
#define STAI_RPS_TOF_IN_SIZES \
  { \
    3200 \
  }
#define STAI_RPS_TOF_IN_SIZES_BYTES \
  { \
    3200 \
  }

#define STAI_RPS_TOF_IN_1_ALIGNMENT (32)
#define STAI_RPS_TOF_IN_1_NAME "Input_0_out_0"
#define STAI_RPS_TOF_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_IN_1_FORMAT (STAI_FORMAT_U8)
#define STAI_RPS_TOF_IN_1_SIZE (3200)
#define STAI_RPS_TOF_IN_1_SIZE_BYTES (3200)
#define STAI_RPS_TOF_IN_1_CHANNEL (1)
#define STAI_RPS_TOF_IN_1_HEIGHT (50)
#define STAI_RPS_TOF_IN_1_WIDTH (64)
#define STAI_RPS_TOF_IN_1_BATCH (1)
#define STAI_RPS_TOF_IN_1_RANK (4)
#define STAI_RPS_TOF_IN_1_SHAPE \
  { \
    1, 50, 64, 1 \
  }
#define STAI_RPS_TOF_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_IN_1_SCALES \
  { \
    1 \
  }
#define STAI_RPS_TOF_IN_1_OFFSETS \
  { \
    0 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_RPS_TOF_OUT_NUM (1)
#define STAI_RPS_TOF_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_RPS_TOF_OUT_NAMES \
  { \
    "Quantize_37_out_0" \
  }
#define STAI_RPS_TOF_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_RPS_TOF_OUT_SIZES \
  { \
    4 \
  }
#define STAI_RPS_TOF_OUT_SIZES_BYTES \
  { \
    4 \
  }

#define STAI_RPS_TOF_OUT_1_ALIGNMENT (32)
#define STAI_RPS_TOF_OUT_1_NAME "Quantize_37_out_0"
#define STAI_RPS_TOF_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_RPS_TOF_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_OUT_1_SIZE (4)
#define STAI_RPS_TOF_OUT_1_SIZE_BYTES (4)
#define STAI_RPS_TOF_OUT_1_CHANNEL (1)
#define STAI_RPS_TOF_OUT_1_HEIGHT (1)
#define STAI_RPS_TOF_OUT_1_WIDTH (4)
#define STAI_RPS_TOF_OUT_1_RANK (2)
#define STAI_RPS_TOF_OUT_1_SHAPE \
  { \
    1, 4 \
  }
#define STAI_RPS_TOF_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_RPS_TOF_OUT_1_OFFSETS \
  { \
    -128 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_RPS_TOF_WEIGHTS_NUM (30)
#define STAI_RPS_TOF_WEIGHTS_ALIGNMENTS \
  { \
    32, 16, 32, 32, 32, 32, 32, 16, 16, 32, 32, 32, 16, 32, 32, 32, 16, 32, 32, 32, 32, 32, 32, 16, 32, 16, 16, 32, 32, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_NAMES \
  { \
    "Quantize_3_y_scale", "Quantize_3_y_zero_point", "Conv2D_5_weights", "Conv2D_11_weights", "Conv2D_17_weights", "Conv2D_23_weights", "Gemm_29_weights_transposed_3", "Gemm_33_weights_transposed_9", "Conv2D_5_zero_off_14", "Conv2D_5_off_bias_20", "Conv2D_11_zero_off_23", "Conv2D_11_off_bias_29", "Conv2D_17_zero_off_32", "Conv2D_17_off_bias_38", "Conv2D_23_zero_off_41", "Conv2D_23_off_bias_47", "Gemm_29_conv_4_zero_off_50", "Gemm_29_conv_4_off_bias_56", "Gemm_33_conv_10_zero_off_59", "Gemm_33_conv_10_off_bias_65", "Conv2D_5_off_bias_18_A_16_184", "Conv2D_11_off_bias_27_A_16_186", "Conv2D_17_off_bias_36_A_16_188", "Conv2D_23_off_bias_45_A_16_190", "Gemm_29_conv_4_off_bias_54_A_16_192", "Gemm_33_conv_10_off_bias_63_A_16_194", "Gemm_33_squeeze_y_11_196_atonn_internal_scale", "Gemm_33_squeeze_y_11_196_atonn_internal_offset", "Softmax_36_200_atonn_internal_scale", "Softmax_36_200_atonn_internal_offset" \
  }
#define STAI_RPS_TOF_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_FLOAT32, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_Q15, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7 \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES \
  { \
    1, 1, 144, 3456, 6912, 6912, 36864, 128, 1, 16, 1, 24, 1, 32, 1, 24, 1, 32, 1, 4, 16, 24, 32, 24, 32, 4, 1, 1, 1, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES_BYTES \
  { \
    4, 1, 144, 3456, 6912, 6912, 36864, 128, 1, 64, 1, 96, 1, 128, 1, 96, 1, 128, 1, 16, 32, 48, 64, 48, 64, 8, 4, 1, 4, 1 \
  }

#define STAI_RPS_TOF_WEIGHTS_1_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_1_NAME "Quantize_3_y_scale"
#define STAI_RPS_TOF_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_1_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_1_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_1_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_1_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_1_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_1_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_1_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_1_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_1_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_1_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_1_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_2_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_2_NAME "Quantize_3_y_zero_point"
#define STAI_RPS_TOF_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_2_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_2_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_2_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_2_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_2_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_2_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_2_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_2_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_2_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_2_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_3_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_3_NAME "Conv2D_5_weights"
#define STAI_RPS_TOF_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_3_SIZE (144)
#define STAI_RPS_TOF_WEIGHTS_3_SIZE_BYTES (144)
#define STAI_RPS_TOF_WEIGHTS_3_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_3_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_3_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_3_BATCH (1)
#define STAI_RPS_TOF_WEIGHTS_3_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_3_SHAPE \
  { \
    16, 3, 3, 1 \
  }
#define STAI_RPS_TOF_WEIGHTS_3_SCALE_OFFSET_NUM (16)
#define STAI_RPS_TOF_WEIGHTS_3_SCALES \
  { \
    7.74587624619016e-06, 7.78836420067819e-06, 6.39686413705931e-06, 6.13314841757528e-06, 8.11318841442699e-06, 9.28466488403501e-06, 8.00232010078616e-06, 6.42193799649249e-06, 7.10603035258828e-06, 6.64853541820776e-06, 7.20250181984738e-06, 1.05182689367211e-05, 8.05430772743421e-06, 6.56422980682692e-06, 8.69711857376387e-06, 5.8530881688057e-06 \
  }
#define STAI_RPS_TOF_WEIGHTS_3_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_4_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_4_NAME "Conv2D_11_weights"
#define STAI_RPS_TOF_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_4_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_4_SIZE (3456)
#define STAI_RPS_TOF_WEIGHTS_4_SIZE_BYTES (3456)
#define STAI_RPS_TOF_WEIGHTS_4_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_4_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_4_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_4_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_4_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_4_SHAPE \
  { \
    24, 2, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_4_SCALE_OFFSET_NUM (24)
#define STAI_RPS_TOF_WEIGHTS_4_SCALES \
  { \
    0.00148110766895115, 0.00153469666838646, 0.00162304833065718, 0.00167655851691961, 0.00211146520450711, 0.00141325709410012, 0.00178695865906775, 0.00198337901383638, 0.00164974317885935, 0.00173893920145929, 0.00196518027223647, 0.00146768102422357, 0.00156269234139472, 0.0016496047610417, 0.00154882238712162, 0.00164554372895509, 0.00203010975383222, 0.00168740306980908, 0.00141964503563941, 0.00137072522193193, 0.00176705361809582, 0.00159852567594498, 0.00201393431052566, 0.00147586199454963 \
  }
#define STAI_RPS_TOF_WEIGHTS_4_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_5_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_5_NAME "Conv2D_17_weights"
#define STAI_RPS_TOF_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_5_SIZE (6912)
#define STAI_RPS_TOF_WEIGHTS_5_SIZE_BYTES (6912)
#define STAI_RPS_TOF_WEIGHTS_5_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_5_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_5_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_5_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_5_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_5_SHAPE \
  { \
    32, 3, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_5_SCALE_OFFSET_NUM (32)
#define STAI_RPS_TOF_WEIGHTS_5_SCALES \
  { \
    0.00280312146060169, 0.00167371425777674, 0.00172488216776401, 0.00244582933373749, 0.00153417605906725, 0.00203319382853806, 0.00187642872333527, 0.00182832567952573, 0.00159165181685239, 0.00195601652376354, 0.00153705209959298, 0.00191543123219162, 0.00156161864288151, 0.00161989219486713, 0.00173062551766634, 0.0016643803101033, 0.00153172167483717, 0.00121053878683597, 0.00182324345223606, 0.00129393930546939, 0.00168160651810467, 0.00185738503932953, 0.00166744971647859, 0.00166947639081627, 0.00181156303733587, 0.0012999203754589, 0.00175735750235617, 0.00185915036126971, 0.00151629350148141, 0.00167399155907333, 0.00187943177297711, 0.00173373345751315 \
  }
#define STAI_RPS_TOF_WEIGHTS_5_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_6_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_6_NAME "Conv2D_23_weights"
#define STAI_RPS_TOF_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_6_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_6_SIZE (6912)
#define STAI_RPS_TOF_WEIGHTS_6_SIZE_BYTES (6912)
#define STAI_RPS_TOF_WEIGHTS_6_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_6_HEIGHT (3)
#define STAI_RPS_TOF_WEIGHTS_6_WIDTH (3)
#define STAI_RPS_TOF_WEIGHTS_6_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_6_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_6_SHAPE \
  { \
    24, 4, 3, 3, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_6_SCALE_OFFSET_NUM (24)
#define STAI_RPS_TOF_WEIGHTS_6_SCALES \
  { \
    0.00258686300367117, 0.00206675752997398, 0.00158733117859811, 0.00153720786329359, 0.00243278546258807, 0.00197122571989894, 0.00166602595709264, 0.00172801979351789, 0.0016780155710876, 0.00171061104629189, 0.00151969108264893, 0.00142635952215642, 0.00137993111275136, 0.00225930009037256, 0.00133788958191872, 0.00211898586712778, 0.00207851221784949, 0.00155499239917845, 0.00179154507350177, 0.00157080928329378, 0.00260304682888091, 0.00152271310798824, 0.00239923549816012, 0.00240488746203482 \
  }
#define STAI_RPS_TOF_WEIGHTS_6_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_7_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_7_NAME "Gemm_29_weights_transposed_3"
#define STAI_RPS_TOF_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_7_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_7_SIZE (36864)
#define STAI_RPS_TOF_WEIGHTS_7_SIZE_BYTES (36864)
#define STAI_RPS_TOF_WEIGHTS_7_CHANNEL (1152)
#define STAI_RPS_TOF_WEIGHTS_7_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_7_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_7_BATCH (128)
#define STAI_RPS_TOF_WEIGHTS_7_RANK (5)
#define STAI_RPS_TOF_WEIGHTS_7_SHAPE \
  { \
    32, 9, 1, 1, 128 \
  }
#define STAI_RPS_TOF_WEIGHTS_7_SCALE_OFFSET_NUM (32)
#define STAI_RPS_TOF_WEIGHTS_7_SCALES \
  { \
    0.00159043038729578, 0.00212819618172944, 0.00172279274556786, 0.00175947265233845, 0.00179263250902295, 0.00161409610882401, 0.00162796606309712, 0.00076011149212718, 0.00072773196734488, 0.000603756867349148, 0.00167171854991466, 0.00166353350505233, 0.0016028507379815, 0.000772871484514326, 0.00159993104171008, 0.000632707378827035, 0.00143792398739606, 0.000775720691308379, 0.00160493329167366, 0.000834457343444228, 0.00163690454792231, 0.00178379588760436, 0.00148843950591981, 0.00161498575471342, 0.00151392270345241, 0.00165395101066679, 0.00151391257531941, 0.00151880946941674, 0.00141154183074832, 0.00156277394853532, 0.000604042550548911, 0.000635407690424472 \
  }
#define STAI_RPS_TOF_WEIGHTS_7_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_8_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_8_NAME "Gemm_33_weights_transposed_9"
#define STAI_RPS_TOF_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_8_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_8_SIZE (128)
#define STAI_RPS_TOF_WEIGHTS_8_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_8_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_8_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_8_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_8_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_8_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_8_SHAPE \
  { \
    4, 1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_8_SCALE_OFFSET_NUM (4)
#define STAI_RPS_TOF_WEIGHTS_8_SCALES \
  { \
    0.00434471108019352, 0.00318865873850882, 0.00341434706933796, 0.00333979330025613 \
  }
#define STAI_RPS_TOF_WEIGHTS_8_OFFSETS \
  { \
    0, 0, 0, 0 \
  }

#define STAI_RPS_TOF_WEIGHTS_9_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_9_NAME "Conv2D_5_zero_off_14"
#define STAI_RPS_TOF_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_9_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_9_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_9_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_9_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_9_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_9_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_9_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_9_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_9_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_9_SCALES \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_9_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_10_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_10_NAME "Conv2D_5_off_bias_20"
#define STAI_RPS_TOF_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_10_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_10_SIZE (16)
#define STAI_RPS_TOF_WEIGHTS_10_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_10_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_10_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_10_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_10_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_10_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_10_SHAPE \
  { \
    2, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_10_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_10_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_10_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_11_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_11_NAME "Conv2D_11_zero_off_23"
#define STAI_RPS_TOF_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_11_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_11_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_11_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_11_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_11_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_11_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_11_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_11_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_11_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_11_SCALES \
  { \
    0.00423772726207972 \
  }
#define STAI_RPS_TOF_WEIGHTS_11_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_12_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_12_NAME "Conv2D_11_off_bias_29"
#define STAI_RPS_TOF_WEIGHTS_12_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_12_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_12_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_12_SIZE_BYTES (96)
#define STAI_RPS_TOF_WEIGHTS_12_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_12_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_12_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_12_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_12_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_12_SHAPE \
  { \
    3, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_12_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_12_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_12_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_13_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_13_NAME "Conv2D_17_zero_off_32"
#define STAI_RPS_TOF_WEIGHTS_13_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_13_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_13_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_13_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_13_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_13_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_13_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_13_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_13_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_13_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_13_SCALES \
  { \
    0.0104388082399964 \
  }
#define STAI_RPS_TOF_WEIGHTS_13_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_14_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_14_NAME "Conv2D_17_off_bias_38"
#define STAI_RPS_TOF_WEIGHTS_14_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_14_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_14_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_14_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_14_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_14_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_14_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_14_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_14_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_14_SHAPE \
  { \
    4, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_14_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_14_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_14_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_15_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_15_NAME "Conv2D_23_zero_off_41"
#define STAI_RPS_TOF_WEIGHTS_15_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_15_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_15_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_15_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_15_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_15_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_15_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_15_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_15_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_15_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_15_SCALES \
  { \
    0.023015484213829 \
  }
#define STAI_RPS_TOF_WEIGHTS_15_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_16_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_16_NAME "Conv2D_23_off_bias_47"
#define STAI_RPS_TOF_WEIGHTS_16_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_16_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_16_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_16_SIZE_BYTES (96)
#define STAI_RPS_TOF_WEIGHTS_16_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_16_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_16_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_16_BATCH (8)
#define STAI_RPS_TOF_WEIGHTS_16_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_16_SHAPE \
  { \
    3, 1, 1, 8 \
  }
#define STAI_RPS_TOF_WEIGHTS_16_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_16_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_16_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_17_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_17_NAME "Gemm_29_conv_4_zero_off_50"
#define STAI_RPS_TOF_WEIGHTS_17_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_17_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_17_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_17_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_17_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_17_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_17_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_17_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_17_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_17_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_17_SCALES \
  { \
    0.0430470928549767 \
  }
#define STAI_RPS_TOF_WEIGHTS_17_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_18_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_18_NAME "Gemm_29_conv_4_off_bias_56"
#define STAI_RPS_TOF_WEIGHTS_18_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_RPS_TOF_WEIGHTS_18_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_18_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_18_SIZE_BYTES (128)
#define STAI_RPS_TOF_WEIGHTS_18_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_18_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_18_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_18_BATCH (16)
#define STAI_RPS_TOF_WEIGHTS_18_RANK (4)
#define STAI_RPS_TOF_WEIGHTS_18_SHAPE \
  { \
    2, 1, 1, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_18_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_18_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_18_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_19_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_19_NAME "Gemm_33_conv_10_zero_off_59"
#define STAI_RPS_TOF_WEIGHTS_19_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_19_FORMAT (STAI_FORMAT_S8)
#define STAI_RPS_TOF_WEIGHTS_19_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_19_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_19_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_19_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_19_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_19_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_19_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_19_SCALE_OFFSET_NUM (1)
#define STAI_RPS_TOF_WEIGHTS_19_SCALES \
  { \
    0.131228044629097 \
  }
#define STAI_RPS_TOF_WEIGHTS_19_OFFSETS \
  { \
    0 \
  }

#define STAI_RPS_TOF_WEIGHTS_20_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_20_NAME "Gemm_33_conv_10_off_bias_65"
#define STAI_RPS_TOF_WEIGHTS_20_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_20_FORMAT (STAI_FORMAT_S32)
#define STAI_RPS_TOF_WEIGHTS_20_SIZE (4)
#define STAI_RPS_TOF_WEIGHTS_20_SIZE_BYTES (16)
#define STAI_RPS_TOF_WEIGHTS_20_CHANNEL (4)
#define STAI_RPS_TOF_WEIGHTS_20_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_20_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_20_BATCH (4)
#define STAI_RPS_TOF_WEIGHTS_20_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_20_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_RPS_TOF_WEIGHTS_20_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_20_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_20_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_21_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_21_NAME "Conv2D_5_off_bias_18_A_16_184"
#define STAI_RPS_TOF_WEIGHTS_21_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_21_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_21_SIZE (16)
#define STAI_RPS_TOF_WEIGHTS_21_SIZE_BYTES (32)
#define STAI_RPS_TOF_WEIGHTS_21_CHANNEL (16)
#define STAI_RPS_TOF_WEIGHTS_21_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_21_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_21_BATCH (16)
#define STAI_RPS_TOF_WEIGHTS_21_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_21_SHAPE \
  { \
    1, 1, 16 \
  }
#define STAI_RPS_TOF_WEIGHTS_21_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_21_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_21_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_22_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_22_NAME "Conv2D_11_off_bias_27_A_16_186"
#define STAI_RPS_TOF_WEIGHTS_22_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_22_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_22_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_22_SIZE_BYTES (48)
#define STAI_RPS_TOF_WEIGHTS_22_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_22_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_22_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_22_BATCH (24)
#define STAI_RPS_TOF_WEIGHTS_22_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_22_SHAPE \
  { \
    1, 1, 24 \
  }
#define STAI_RPS_TOF_WEIGHTS_22_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_22_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_22_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_23_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_23_NAME "Conv2D_17_off_bias_36_A_16_188"
#define STAI_RPS_TOF_WEIGHTS_23_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_23_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_23_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_23_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_23_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_23_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_23_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_23_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_23_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_23_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_23_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_23_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_23_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_24_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_24_NAME "Conv2D_23_off_bias_45_A_16_190"
#define STAI_RPS_TOF_WEIGHTS_24_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_24_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_24_SIZE (24)
#define STAI_RPS_TOF_WEIGHTS_24_SIZE_BYTES (48)
#define STAI_RPS_TOF_WEIGHTS_24_CHANNEL (24)
#define STAI_RPS_TOF_WEIGHTS_24_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_24_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_24_BATCH (24)
#define STAI_RPS_TOF_WEIGHTS_24_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_24_SHAPE \
  { \
    1, 1, 24 \
  }
#define STAI_RPS_TOF_WEIGHTS_24_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_24_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_24_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_25_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_25_NAME "Gemm_29_conv_4_off_bias_54_A_16_192"
#define STAI_RPS_TOF_WEIGHTS_25_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_25_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_25_SIZE (32)
#define STAI_RPS_TOF_WEIGHTS_25_SIZE_BYTES (64)
#define STAI_RPS_TOF_WEIGHTS_25_CHANNEL (32)
#define STAI_RPS_TOF_WEIGHTS_25_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_25_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_25_BATCH (32)
#define STAI_RPS_TOF_WEIGHTS_25_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_25_SHAPE \
  { \
    1, 1, 32 \
  }
#define STAI_RPS_TOF_WEIGHTS_25_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_25_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_25_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_26_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_26_NAME "Gemm_33_conv_10_off_bias_63_A_16_194"
#define STAI_RPS_TOF_WEIGHTS_26_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_RPS_TOF_WEIGHTS_26_FORMAT (STAI_FORMAT_Q15)
#define STAI_RPS_TOF_WEIGHTS_26_SIZE (4)
#define STAI_RPS_TOF_WEIGHTS_26_SIZE_BYTES (8)
#define STAI_RPS_TOF_WEIGHTS_26_CHANNEL (4)
#define STAI_RPS_TOF_WEIGHTS_26_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_26_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_26_BATCH (4)
#define STAI_RPS_TOF_WEIGHTS_26_RANK (3)
#define STAI_RPS_TOF_WEIGHTS_26_SHAPE \
  { \
    1, 1, 4 \
  }
#define STAI_RPS_TOF_WEIGHTS_26_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_26_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_26_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_27_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_27_NAME "Gemm_33_squeeze_y_11_196_atonn_internal_scale"
#define STAI_RPS_TOF_WEIGHTS_27_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_27_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_27_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_27_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_27_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_27_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_27_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_27_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_27_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_27_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_27_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_27_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_28_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_28_NAME "Gemm_33_squeeze_y_11_196_atonn_internal_offset"
#define STAI_RPS_TOF_WEIGHTS_28_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_28_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_28_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_28_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_28_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_28_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_28_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_28_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_28_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_28_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_28_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_28_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_29_ALIGNMENT (32)
#define STAI_RPS_TOF_WEIGHTS_29_NAME "Softmax_36_200_atonn_internal_scale"
#define STAI_RPS_TOF_WEIGHTS_29_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_29_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_RPS_TOF_WEIGHTS_29_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_29_SIZE_BYTES (4)
#define STAI_RPS_TOF_WEIGHTS_29_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_29_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_29_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_29_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_29_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_29_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_29_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_29_OFFSETS \
  { \
  }

#define STAI_RPS_TOF_WEIGHTS_30_ALIGNMENT (16)
#define STAI_RPS_TOF_WEIGHTS_30_NAME "Softmax_36_200_atonn_internal_offset"
#define STAI_RPS_TOF_WEIGHTS_30_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_RPS_TOF_WEIGHTS_30_FORMAT (STAI_FORMAT_Q7)
#define STAI_RPS_TOF_WEIGHTS_30_SIZE (1)
#define STAI_RPS_TOF_WEIGHTS_30_SIZE_BYTES (1)
#define STAI_RPS_TOF_WEIGHTS_30_CHANNEL (1)
#define STAI_RPS_TOF_WEIGHTS_30_HEIGHT (1)
#define STAI_RPS_TOF_WEIGHTS_30_WIDTH (1)
#define STAI_RPS_TOF_WEIGHTS_30_RANK (1)
#define STAI_RPS_TOF_WEIGHTS_30_SHAPE \
  { \
    1 \
  }
#define STAI_RPS_TOF_WEIGHTS_30_SCALE_OFFSET_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_30_SCALES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_30_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_RPS_TOF_WEIGHTS_NUM (0)
#define STAI_RPS_TOF_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_NAMES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_FORMATS \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES \
  { \
  }
#define STAI_RPS_TOF_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_RPS_TOF_ACTIVATIONS_NUM (0)
#define STAI_RPS_TOF_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_RPS_TOF_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_RPS_TOF_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_RPS_TOF_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_RPS_TOF_ORIGIN_MODEL_NAME "rps_int8_OE_3_3_1"
#define STAI_RPS_TOF_C_MODEL_NAME "rps_tof"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_RPS_TOF_H
